/**
 * Created by maraujo on 3/16/17.
 */
import {Service, Inject} from "typedi";
import {Outcome, IService} from "../commons/index";
import {CountryModel} from "./country.model";

@Service()
export class CountryService implements IService<CountryModel> {


    create(country: CountryModel) {
    }

    update(country: CountryModel) {
    }

    deleteById(id: number) {
    }

    async findById(id: number) {
        let brazil: CountryModel = new CountryModel();

        brazil.id = 23;
        brazil.geoname_id = 3469034;
        brazil.name = "Brasil";
        brazil.ascii_name = "Federative Republic of Brazil";
        brazil.alternate_names = "An Bhrasail,An Bhrasaíl,Ba Tay (Bra-xin),Ba Tây (Bra-xin),Baraasiil,Beresiil,Berezili,Birazil,Bra-xin,Braasiil,Brasiilia,Brasil,Brasila,Brasilaen,Brasile,Brasili,Brasilia,Brasilie,Brasilien,Brasilië,Brasilän,Brasilía,Brasíle,Brasīl,Braxil,Braziel,Braziilii,Brazil,Brazil nutome,Brazili,Brazilia,Brazilie,Brazilija,Braziliya,Brazilië,Brazilo,Brazylia,Brazylje,Brazíl,Brazília,Brazílie,Brazīlija,Brażil,Breasail,Bresi,Bresil,Brezil,Brezila,Brezili,Brezilya,Brezílɛ,Brezîli,Brèsil,Brési,Brésil,Buraziiri,Burezili,Estados Unidos do Brasil,Estados Unidos do Brazil,Federative Republic of Brazil,Mnulezile,Orileede Barasili,Orílẹ́ède Bàràsílì,Palakila,Palasili,Palāsili,Republica Federativa do Brasil,Republica dos Estados Unidos do Brasil,República Federativa do Brasil,República dos Estados Unidos do Brasil,United States of Brazil,albrazyl,ba xi,beulajil,braajila,brajhila,brajil,brajila,brasil,brasila,brazila,brazilia,brazyl,brazyly,brejil,brzyl,burajiru,burajiru lian bang gong he guo,i-Brazil,pirecil,piresil,prathes brasil,razgu'e,Βραζιλία,Бразил,Бразили,Бразилия,Бразилія,Бразілія,Браѕил,Բրազիլիա,בראזיליע,ברזיל,البرازيل,برازىلىيە,برازيل,برازیل,برازیلی,برزیل,ब्राज़िल,ब्राजिल,ब्राजील,ब्राझिल,ब्रास़ील,ব্রাজিল,ব্ৰাজিল,બ્રાઝિલ,ବ୍ରାଜିଲ୍,பிரேசில்,பிரேஸில்,బ్రజిల్,ಬ್ರೆಜಿಲ್,ബ്രസീല്‍,බ්‍රසීලය,บราซิล,ประเทศบราซิล,ບຼາຊິວ,པུ་རུ་ཟིལ,བ་རཱ་ཛིལ།,བཱརཱ་ཛིལ,ဘရာဇီး,ბრაზილია,ብራዚል,ប្រេស៊ីល,ブラジル,ブラジル連邦共和国,巴西,ꀠꑭ,브라질";
        brazil.latitude = -10;
        brazil.longitude = -55;
        brazil.feature_class = "A";
        brazil.feature_code = "PCLI";
        brazil.country_code = "BR";
        brazil.cc2 = "";
        brazil.admin1_code = "00";
        brazil.admin2_code = "";
        brazil.admin3_code = "";
        brazil.admin4_code = "";
        brazil.population = 201103330;
        brazil.elevation = 0;
        brazil.gtopo30 = 258;
        brazil.modification_date = "04/03/2013";


        return Outcome.ResultSuccess(brazil);
    }

    async getAll() {
        let countries: Array<CountryModel> = this.getMocCountries();
        return Outcome.ResultsSuccess(countries);
    }

    getMocCountries(): Array<CountryModel> {
        return [{
                "id": 7,
                "geoname_id": 3351879,
                "name": "Angola",
                "ascii_name": "Republic of Angola",
                "alternate_names": "'Enikola,Africa Ocidental Portuguesa,An'nkola,Ang-go-la,Ang-go-la (Angola),Angola,Angola nutome,Angolaea,Angole,Angolia,Angolo,Angoläa,Angolë,Angoola,Angora,Angòla,Angóla,Ankola,Anngolaa,Colonia de Angola,Colónia de Angola,Estado de Angola,Langolaen,Langolän,Ngola,Orileede Aangola,Orílẹ́ède Ààngólà,People's Republic of Angola,People’s Republic of Angola,Portugiesisch Westafrika,Portuguese West Africa,Provincia de Angola,Província de Angola,Republic of Angola,Republica Popular de Angola,Republica de Angola,República Popular de Angola,República de Angola,amgola,an ge la,ang-golla,angeala,anghwla,angola,angora,angora gong he guo,angwla,anjwla,ankola,engola,i-Angola,yangwla,África Ocidental Portuguesa,Ăng-gô-la,Ăng-gô-la (Angola),ʻEnikola,Αγκόλα,Ανγκόλα,Ангола,Анґола,Անգոլա,אנגולה,آنگولا,أنجولا,أنغولا,ئانگولا,ئەنگۆلا,انغولا,انګولا,انگولا,अँगोला,अंगोला,अङ्गोला,অ্যাঙ্গোলা,এঙ্গোলা,এ্যাঙ্গোলা,અંગોલા,ଆଙ୍ଗୋଲା,அங்கோலா,అంగోలా,ಅಂಗೋಲಾ,അംഗോള,ඇන්ගෝලාව,ประเทศแองโกลา,แองโกลา,ອັນໂກລາ,ཨང་གཽ་ལ།,အင်ဂိုလာ,ანგოლა,አንጎላ,አንጐላ,អង់ហ្គោឡា,អាង់កូឡា,アンゴラ,アンゴラ共和国,安哥拉,앙골라",
                "latitude": -12.5,
                "longitude": 18.5,
                "feature_class": "A",
                "feature_code": "PCLI",
                "country_code": "AO",
                "cc2": "",
                "admin1_code": "00",
                "admin2_code": "",
                "admin3_code": "",
                "admin4_code": "",
                "population": 13068161,
                "elevation": 0,
                "gtopo30": 1355,
                "timezone": "Africa/Luanda",
                "modification_date": "04/03/2013"
            },
            {
                "id": 4,
                "geoname_id": 3576396,
                "name": "Antigua and Barbuda",
                "ascii_name": "Antigua and Barbuda",
                "alternate_names": "Aintige agus Barbuda,Aintíge agus Barbúda,An-ti-gu-a va Ba-bu-ga,An-ti-gu-a va Ba-bu-ga (Antigua va Barbuda),An-ti-gu-a và Ba-bu-đa,An-ti-gu-a và Ba-bu-đa (Antigua và Barbuda),Anitikua mo Palaputa,Antiga e Barbuda,Antiga e Barbuda - Antigua and Barbuda,Antiga ha Barbuda,Antiga mpe Barbuda,Antiga mpé Barbuda,Antiga ne Barbuda,Antiga sy Barboda,Antiga-ni-Barbuda,Antigoa-et-Barbuda,Antigua Presidency,Antigua a Barbados,Antigua a Barbuda,Antigua aamma Barbuda,Antigua and Barbuda,Antigua at Barbuda,Antigua dan Barbuda,Antigua dhe Barbuda,Antigua e Barbuda,Antigua en Barbuda,Antigua en Barbûda,Antigua es Barbuda,Antigua et Barbuda,Antigua eta Barbuda,Antigua ha Barbuda,Antigua i Barbuda,Antigua in Barbuda,Antigua iyo Barbuda,Antigua ja Barbuda,Antigua kple Barbuda nutome,Antigua le Barbuda,Antigua me Barbuda,Antigua na Barbuda,Antigua ne Baabuda,Antigua ne Barbuda,Antigua och Barbuda,Antigua og Barbuda,Antigua si Barbuda,Antigua u Berbuda,Antigua un Barbuda,Antigua und Barbuda,Antigua ve Barbuda,Antigua y Barbuda,Antigua és Barbuda,Antigua și Barbuda,Antigua-Barbuda,Antigua-et-Barbuda,Antiguwaa e Barbudaa,Antigva i Barbuda,Antigva in Barbuda,Antigva ir Barbuda,Antigva og Barbuda,Antigva un Barbuda,Antigve i Barbuda,Antigvo-Barbudo,Antigwa a Barbuda,Antigwa da Barbuba,Antigwa na Baribuda,Antigwa ne Barabuda,Antigûa û Berbûda,Antinkoua kai Mparmpounta,Antiqua et Barbuda,Antiqua və Barbuda,Antygua i Barbuda,Antígua e Barbuda,Antígva og Barbúda,Antîgua na Barbûda,Colony of Antigua,Lantigeaen e Barbudeaen,Lantigeän e Barbudeän,Orileede Aantigua ati Baribuda,Orílẹ́ède Ààntígúà àti Báríbúdà,Presidency of Antigua,State of Antigua,aentiga babuda,amtigva ani barbuda,an ti gua he ba bu da,antiga babuda,antigu'a ebam barabuda,antiguababuda,antiguva mattu barbuda,antiguya o barbuda,antigva,antigva mariyu barbuda,antikuva marrum parputa,antygha wbarbwda,antygha wbrbwda,antyghwa wbrbwda,antygwa w barbwda,antyjwa wbrbwda,entigu'a ane barabuda,entigu'a aura barabuda,entigu'a ra barabuda,entiguva aura barabuda,entiguya ebam barbuda,entiguya o barabuda,i-Antigua and Barbuda,yantygwa w barbwda,́Antigua kple Barbuda nutome,Αντίγκουα και Μπαρμπούντα,Антигва и Барбуда,Антигве и Барбуда,Антигуа и Барбуда,Антигуа і Барбуда,Антиґуа і Барбуда,Антыгуа і Барбуда,Антігуа і Барбуда,Անտիգուա-Բարբուդա,אנטיגואה וברבודה,אנטיגווה וברבודה,آنتیگوا و باربودا,أنتيجوا وبربودا,أنتيغا وباربودا,أنتيغا وبربودا,ئانتیگوا و باربودا,انتيغوا وبربودا,انٹیگوا اور باربودا,انټيګ او بربودا,अँटिग्वा आणि बर्बुडा,अंटीग्वा,एंटिगुआ और बारबुडा,एन्टिगुआ र बारबुडा,एन्टिगुवा और बारबूडा,আন্টিগুয়া ও বার্বুডা,এন্টিগুয়া এবং বার্বুডা,এন্টিগুয়া ও বারবুডা,એન્ટીગુઆ અને બરબુડા,ଆଣ୍ଟିଗୁଆ ଏବଂ ବାରବୁଦା,ஆண்டிகுவா மற்றும் பார்புடா,ఆంటిగ్వా మరియు బార్బుడా,ಆಂಟಿಗುವಾ ಮತ್ತು ಬರ್ಬುಡಾ,ആന്‍റിഗ്വയും ബര്‍ബുഡയും,ඇන්ටිගුවා සහ බාබියුඩා,แอนติกาและบาร์บูดา,ཨེན་ཊི་གུ་དང་། བྷར་བུ་ཌ།,ანტიგუა და ბარბუდა,አንቲጓ እና ባሩዳ,アンティグアバブーダ,アンティグア・バーブーダ,安提瓜和巴布达,안티가 바부다,앤티가 바부다",
                "latitude": 17.05,
                "longitude": -61.8,
                "feature_class": "A",
                "feature_code": "PCLI",
                "country_code": "AG",
                "cc2": "",
                "admin1_code": "00",
                "admin2_code": "",
                "admin3_code": "",
                "admin4_code": "",
                "population": 86754,
                "elevation": 0,
                "gtopo30": 65,
                "timezone": "America/Antigua",
                "modification_date": "01/18/2012"
            },
            {
                "id": 8,
                "geoname_id": 3865483,
                "name": "Argentina",
                "ascii_name": "Argentine Republic",
                "alternate_names": "'Asenitina,A Can GJinh (Argentina),Ac-hen-ti-na,Agyɛntina,Ajantin,Ajentina,Alijantine,An Airgintin,An Airgintín,Arc'hantina,Archentina,Arcʼhantina,Argencina,Argentena,Argentiina,Argentiinu,Argentin-a,Argentina,Argentina nutome,Argentine,Argentine Republic,Argentinia,Argentinie,Argentinien,Argentinië,Argentino,Argentyna,Argentína,Argentīna,Arghantina,Argintina,Argjentina,Argjentine,Argjentinë,Arhentina,Arhintina,Arigentina,Arijantine,Arizantin,Arizantinɛ,Arjantiin,Arjantin,Arjantiniya,Arjantîn,Arjentina,Arjentinia,Arqentina,Artschenti,Arxentina,Arxentina - Argentina,Arxentitlan,Arxentitlān,Arzantina,Arzantîna,Arzhentina,Arġentina,La Argentina,Largaentaen,Largäntän,Orileede Agentina,Orílẹ́ède Agentínà,Republica Argentina,República Argentina,Yr Ariannin,a gen ting,alarjntyn,aleuhentina,arjantina,arjenta'ina,arjentaina,arjentina,aruzenchin,aruzenchin gong he guo,arzhantyn,getygu'e,i-Argentina,prathes xarcentina,xarcentina,Á Căn Đình (Argentina),Ác-hen-ti-na,ʻAsenitina,Αργεντινή,Аргентина,Аргентына,Аргенціна,Аржентина,Արգենտինա,ארגנטינה,ארגענטינע,آرجنٹین,آرژانتین,ئارجەنتینا,ئارگېنتىنا,ارجنٹائن,ارجنٹینا,ارجنټاين,الأرجنتين,الارجنتين,अर्जन्टीना,अर्जेंटिना,अर्जेंटीना,अर्जेण्टिना,अर्जेन्टीना,আর্জেণ্টাইনা,আর্জেন্টিনা,આર્જેન્ટીના,ଆର୍ଜେଣ୍ଟିନା,அர்ஜெண்டினா,அர்ஜென்டினா,ఆర్జెంటినా,ಅರ್ಜೆಂಟೀನ,ಅರ್ಜೆಂಟೈನಾ,അര്‍ജന്റീന,അര്‍ജന്‍റീന,ආර්ජෙන්ටිනාව,ประเทศอาร์เจนตินา,อาร์เจนตินา,ອາເຈນຕິນາ່,ཨར་ཇེན་ཊི་ན,ཨར་ཇེན་ཊི་ན།,အာဂျင်တီးနား,არგენტინა,አርጀንቲና,អារហ្សង់ទីន,អាហ្សង់ទីន,アルゼンチン,アルゼンチン共和国,阿根廷,아르헨티나",
                "latitude": -34,
                "longitude": -64,
                "feature_class": "A",
                "feature_code": "PCLI",
                "country_code": "AR",
                "cc2": "",
                "admin1_code": "00",
                "admin2_code": "",
                "admin3_code": "",
                "admin4_code": "",
                "population": 41343201,
                "elevation": 0,
                "gtopo30": 189,
                "timezone": "",
                "modification_date": "02/01/2016"
            },
            {
                "id": 10,
                "geoname_id": 2077456,
                "name": "Australia",
                "ascii_name": "Commonwealth of Australia",
                "alternate_names": "'Aositelelia,Ahitereiria,An Astrail,An Astráil,Aostralia,Astralia,Austraalia,Austrailae,Australi,Australia,Australia (Uc),Australia (Úc),Australia nutome,Australie,Australien,Australija,Australio,Australië,Australya,Austràlia,Austrália,Austrálie,Austrālija,Ausztralia,Ausztrália,Autereraria,Avstrali,Avstralia,Avstralija,Avstralijs'kij Sojuz,Avstraliya,Avstrualii,Avustralya,Awistralya,Awstaraaliya,Awstralia,Awstralja,Awstralska,Awstralya,Awusitureliya,Aŭstralio,Commonwealth of Australia,I-Ostreliya,O-tai-li-a,Orileede Astralia,Orílẹ́ède Ástràlìá,Ositali,Ositaraliya,Ositirali,Ositáli,Ostaraalii,Ostareliya,Ostrali,Ostralii  Sotralii,Ostralïi  Sotralïi,Ostrelia,Otereiriya,Uc,ao da li ya,astireliya,astralya,astreli'a,astreliya,hoju,i-Australia,oseuteuleillia,ostreliya,osutoraria,prathes xxsterleiy,sralygu'e,xxsterleiy,yavstyralyyە,Ástralía,Ò-tāi-lī-a,Úc,Ɔstrelia,ʻAositelēlia,ʾwstrlyʾ,Αυστραλία,Австрали,Австралия,Австралија,Австралійський Союз,Австралія,Аустралија,Аўстралія,Ավստրալիա,אויסטראליע,אוסטרליה,אױסטראַליע,آسٹریلیا,آسټراليا,أستراليا,ئاۋستىرالىيە,ئۆسترالیا,استراليا,استرالیا,ܐܘܣܛܪܠܝܐ,އޮސްޓަރުލިޔާ,अष्ट्रेलिया,ऑस्ट्रेलिया,অস্ট্রেলিয়া,অস্ট্রেলিয়া,ઑસ્ટ્રેલિયા,ଅଷ୍ଟ୍ରେଲିଆ,ஆஸ்திரேலியா,ఆస్ట్రేలియా,ಆಸ್ಟ್ರೇಲಿಯ,ഓസ്ട്രേലിയ,ඕස්ට්‍රේලියාව,ประเทศออสเตรเลีย,ออสเตรเลีย,ອົອດສະຕາລີ,ཨ་ས་ཐ་ལ་ཡ།,ཨས་ཊེཡེ་ལི་ཡ,ཨསྟྲེ་ལི་ཡ།,ཨོ་སེ་ཐེ་ལི་ཡ།,ဩစတြေးလျှား,ავსტრალია,አውስትሬሊያ,អូស្ត្រាលី,‘ostaruliya,オーストラリア,澳大利亚,澳大利亞,오스트레일리아,호주",
                "latitude": -25,
                "longitude": 135,
                "feature_class": "A",
                "feature_code": "PCLI",
                "country_code": "AU",
                "cc2": "",
                "admin1_code": "00",
                "admin2_code": "",
                "admin3_code": "",
                "admin4_code": "",
                "population": 21515754,
                "elevation": 0,
                "gtopo30": 269,
                "timezone": "",
                "modification_date": "02/01/2017"
            },
            {
                "id": 24,
                "geoname_id": 3572887,
                "name": "Bahamas",
                "ascii_name": "Commonwealth of The Bahamas",
                "alternate_names": "Ba-ha-ma,Ba-ha-ma (Bahamas),Bagama Adalary,Bagami,Bagams'ki Ostrovi,Bagamskia astravy,Bagamskie ostrova,Bagamy,Bahaamas,Bahama,Bahama Islands,Bahama saared,Bahama's,Bahama-szigetek,Bahamaas,Bahamaeyjar,Bahamak,Bahamalar,Bahamas,Bahamas nutome,Bahamasa,Bahamase,Bahamasi,Bahamasɛ,Bahamat,Bahama’s,Bahamen,Bahames,Bahamet,Bahami,Bahamner,Bahamoj,Bahamos,Bahamu salas,Bahamu salos,Bahamuaens,Bahamuäns,Bahamy,Bahamák,Bahamų salos,Bahâmasa,Bakhame,Bakhami,Bakhamski O-vi,Bakhamski Ostrovi,Bakhamski ostrovi,Baħamas,Bhahamas,Colony of the Bahamas,Commonwealth of The Bahamas,Insulae Bahamenses,Mpachames,Na Bahamai,Na Bahámaí,Orileede Bahamasi,Orílẹ́ède Bàhámásì,Pahama,The Bahamas,Y Bahamas,Ynysow Bahama,albahama,albhama,ba ha ma,bahama,bahama dbipapunja,bahama guo,bahamaja,bahamas,bahamasa,bahamaza,bhamas,i-Bahamas,pahamas,prathes bahamas,Μπαχάμες,Багами,Багамские острова,Багамскія астравы,Багамські Острови,Багамы,Бахаме,Бахами,Бахамски О-ви,Бахамски Острови,Бахамски острови,Բահամներ,איי בהאמה,איי הבהמה,באהאמה  איי,الباهاما,البهاما,باهاما,باھاما,بهاماس,بہاماس,بەھاما,बहामा,बहामाज,बहामाज़,बहामास,বাহামা,বাহামা দ্বীপপুঞ্জ,બહામાસ,ବାହାମାସ୍,பஹாமாஸ்,బహామాస్,ಬಹಾಮಾಸ್,ബഹാമാസ്,බහමාස්,บาฮามาส,ประเทศบาฮามาส,ບາຮາມາສ,བྷཱ་མས྄།,ဘဟားမား,ბაჰამის კუნძულები,ባሃማስ,បាហាមាស,បាហាម៉ា,バハマ,バハマ国,巴哈马,바하마",
                "latitude": 25.04082,
                "longitude": -77.37122,
                "feature_class": "A",
                "feature_code": "PCLI",
                "country_code": "BS",
                "cc2": "",
                "admin1_code": "00",
                "admin2_code": "",
                "admin3_code": "",
                "admin4_code": "",
                "population": 301790,
                "elevation": 0,
                "gtopo30": 20,
                "timezone": "America/Nassau",
                "modification_date": "01/06/2012"
            },
            {
                "id": 13,
                "geoname_id": 3374084,
                "name": "Barbados",
                "ascii_name": "Barbados",
                "alternate_names": "Baabados,Baarbadoos,Babadosi,Bac-ba-got,Barabada,Barabadosi,Barabâda,Barbada,Barbadas,Barbade,Barbadeaen,Barbadeän,Barbadhos,Barbadi,Barbado,Barbadoes,Barbadoos,Barbados,Barbados nutome,Barbadosa,Barbadosas,Barbadosi,Barbadosin Orn,Barbadot,Barbaduosos,Barbadus,Barbady,Barbadós,Barbata,Barbaus,Barbàdos,Barbâda,Barbåde,Barebade,Barubadosi,Barɛbadɛ,Bhabhadosi,Bác-ba-đốt,Bárbádọ̀s,Colony of Barbados,Hashkʼaan Bikéyah,IBhadosi,Lababad,Mparmpantos,Orileede Babadosi,Orílẹ́ède Bábádósì,Papeitosi,Pāpeitosi,ba ba duo si,babados,babeidoseu,barabadasa,barabados,barabadosa,barbados,barbadosa,barbadosi,barbadws,barbedos,barbydws,barubadosu,brbadws,brbdws,i-Barbados,parpatocu,parpatos,prathes barbedos,Μπαρμπάντος,Барбадас,Барбадос,Барбадосин Орн,Բարբադոս,ברבדוס,باربادوس,باربادۆس,بارباڈوس,باربيدوس,بربادوس,ބާބަޑޮސް,बारबाडोस,बार्बाडोस,বারবাদোস,বার্বাডোস,ਬਾਰਬਾਡੋਸ,બાર્બાડોસ,ବାରବାଡସ,ବାରବାଡୋସ୍,பார்படோசு,பார்படோஸ்,బార్బడోస్,ಬಾರ್ಬಡೋಸ್,ബാര്‍ബഡോസ്,ബർബാഡോസ്,බාර්බඩෝස්,บาร์เบโดส,ประเทศบาร์เบโดส,ບາບາຄັອດ,བར་བ་ཌོ་སི།,བཱརྦ་ཌོས྄།,ბარბადოსი,ባርቤዶስ,បារបាដូស,バルバドス,巴巴多斯,바베이도스",
                "latitude": 13.16453,
                "longitude": -59.55165,
                "feature_class": "A",
                "feature_code": "PCLI",
                "country_code": "BB",
                "cc2": "",
                "admin1_code": "00",
                "admin2_code": "",
                "admin3_code": "",
                "admin4_code": "",
                "population": 285653,
                "elevation": 0,
                "gtopo30": 216,
                "timezone": "America/Barbados",
                "modification_date": "10/28/2016"
            },
            {
                "id": 15,
                "geoname_id": 2802361,
                "name": "België",
                "ascii_name": "Kingdom of Belgium",
                "alternate_names": "A'Bheilg,An Bheilg,Behl'gija,Bel'gi,Bel'gii,Bel'gija,Belchica,Belcika,Beldjike,Belejiki,Beleze  Beleziki,Beleziki,Belgia,Belgica,Belgicko,Belgie,Belgien,Belgija,Belgika,Belgio,Belgique,Belgiska,Belgiu,Belgium,Belgium nutome,Belgiyom,België,Belgje,Belgjika,Belgjike,Belgjikë,Belgjo,Belgju,Belgujo,Belgía,Belhika,Beljik,Beljika,Beljium,Belsch,Belsj,Belsum,Belxica,Belxica - Belgie,Belzika,Belçika,Belçîka,Belġju,Bel’gii,Beļģija,Bhelgium,Bi,Bilgasuyu,Bilhika,Biljam,Bubirigi,Bèlgica,Bèlg·ique,Bèljik,Bélgica,Béljika,Bélxica,Bélxica - België,Bêleze  Belezîki,Bɛlgyium,Bɛliziki,Bɛ́ljika,Bỉ,Gwlad Belg,Kingdom of Belgium,Konigreich Belgien,Koninkrijk Belgie,Koninkrijk België,Königreich Belgien,Orileede Begiomu,Orílẹ́ède Bégíọ́mù,Pelesiume,Pow Belg,Royaume de Belgique,Ubelgiji,Ububiligi,Yn Velg,belajiyam,belajiyama,belgia,belgie,beljiyam,beljiyama,belyeiym,berugi,berugi wang guo,bi li shi,blgyh,bljyka,bljym,blzhyk,byljym,gugdrbelgi,i-Belgium,peljiyam,prathes belyeiym,Βέλγιο,Белгия,Белгија,Бельги,Бельгия,Бельгія,Бельґія,Бэльгія,Բելգիա,בלגיה,بلجيكا,بلجيم,بلژیک,بیلجیم,بەلژیک,ܒܠܓܝܟܐ,बेल्जियम,বেলজিয়াম,বেল্জিয়ম,બેલ્જીયમ,ବେଲଜିୟମ୍,பெல்ஜியம்,బెల్జియం,ಬೆಲ್ಜಿಯಮ್,ബെല്‍ജിയം,බෙල්ජියම,ประเทศเบลเยียม,เบลเยียม,ເບວຢຽມ,པེར་ཅིན,བེལ་ཇི་ཡམ།,བེལ་ཇིཡམ,ဘယ်လ်ဂျီယမ်,ბელგია,ቤልጄም,ቤልጅግ,បែលហ្ស៉ិក,ベルギー,ベルギー王国,比利时,벨기에",
                "latitude": 50.75,
                "longitude": 4.5,
                "feature_class": "A",
                "feature_code": "PCLI",
                "country_code": "BE",
                "cc2": "",
                "admin1_code": "00",
                "admin2_code": "",
                "admin3_code": "",
                "admin4_code": "",
                "population": 10403000,
                "elevation": 0,
                "gtopo30": 91,
                "timezone": "Europe/Brussels",
                "modification_date": "10/07/2015"
            },
            {
                "id": 28,
                "geoname_id": 3582678,
                "name": "Belize",
                "ascii_name": "Belize",
                "alternate_names": "An Bheilis,An Bheilís,Balize,Be-li-xe,Beilise,Beles,Belezos,Belice,Belice - Belize,Belici,Beliis,Beliise,Beliiz,Belis,Belisa,Belisaen,Belise,Belisän,Beliz,Beliza,Belizas,Belize,Belize nutome,Belizi,Belizo,Belizy,Belizɛ,Beliże,Belsin Orn,Belís,Belîs,Belîze,Belîzi,Belėzos,Berij,Bhelize,Bilisi,British Honduras,Bélis,Bê-li-xê,Bẹ̀lísè,Hueycopan,Hueyicopan,Huēyicopan,IBhelizi,Mbelise,Orileede Belise,Orílẹ́ède Bèlísẹ̀,Pelise,Wilisi,Yn Veleesh,be lis,belij,belija,belijha,belijhe,belis,beliya,beliz,beliza,belizi,belizu,bellijeu,berizu,blyz,bo li zi,bylayz,bylyz,bʻlyz,bېlyz,i-Belize,pelicu,pelis,pra thes be lis,Μπελίζ,Μπελίσε,Белиз,Белизе,Белисе,Белсин Орн,Беліз,Բելիզ,בליז,בעליז,بليز,بلیز,بيليز,بیلائز,بیلیز,بېلىز,بېلیز,بەلیز,ބެލީޒު,बेलिज,बेलिझ,बेलिझे,बेलीज,बेलीज़,बेलीझ,বেলিজ,বেলিয,ਬੇਲੀਜ਼,બેલીઝ,ବେଲିଜ,ବେଲିଜ୍,பெலிஸ்,பெலீசு,బెలిజ్,బెలీజ్,ಬೆಲಿಜ್,ಬೆಲೀಜ್,ബെലീസ്,බෙලීස්,ประเทศเบลีซ,เบลีซ,ເບລິຊ,བེ་ལི་ཛི།,བེ་ལིཛ།,ဘလိဇ်နိုင်ငံ,ဘေလီဇ်,ბელიზი,ቤሊዘ,ቤሊዝ,បេលីហ្ស,ベリーズ,伯利兹,伯利茲,벨리즈",
                "latitude": 17.25,
                "longitude": -88.75,
                "feature_class": "A",
                "feature_code": "PCLI",
                "country_code": "BZ",
                "cc2": "",
                "admin1_code": "00",
                "admin2_code": "",
                "admin3_code": "",
                "admin4_code": "",
                "population": 314522,
                "elevation": 0,
                "gtopo30": 69,
                "timezone": "America/Belize",
                "modification_date": "06/08/2015"
            },
            {
                "id": 20,
                "geoname_id": 2395170,
                "name": "Bénin",
                "ascii_name": "Republic of Benin",
                "alternate_names": "Be-nanh,Be-nanh (Benin),Beinin,Bene,Benee,Beneen,Benen,Benim,Benin,Benin nutome,Benina,Beninaen,Beninas,Benini,Benino,Beninum,Beninän,Benëen,Benín,Benɛ,Benɛn,Bhenini,Biniin,Binin,Bènin,Bénin,Bê-nanh,Bê-nanh (Benin),Bênîn,Bɛnin,Dahome,Mpenin,Orileede Bene,Orílẹ́ède Bẹ̀nẹ̀,Penini,People's Republic of Benin,People’s Republic of Benin,Republic of Benin,Republic of Dahomey,Republica de Benin,Republique Populaire du Benin,Republique du Benin,Republique du Dahomey,República de Benín,République Populaire du Bénin,République du Bénin,République du Dahomey,bei ning,benaeng,benan,beneng,beni n,benin,benin gong he guo,benina,benini,bnyn,bynn,i-Benin,penin,pra thes beni n,Μπένιν,Μπενίν,Бенин,Бенін,Բենին,בנין,بنين,بنین,بینن,بېنىن,बेनिन,বেনিন,બેનિન,ବେନିନ୍,பெனின்,బెనిన్,ಬೆನಿನ್,ബെനിന്‍,බෙනින්,ประเทศเบนิน,เบนิน,ເບນິນ,བཱེ་ནིན།,ბენინი,ቤኒን,បេណាំង,ベナン,ベニン,ベニン共和国,贝宁,베냉,베넹",
                "latitude": 9.5,
                "longitude": 2.25,
                "feature_class": "A",
                "feature_code": "PCLI",
                "country_code": "BJ",
                "cc2": "",
                "admin1_code": "00",
                "admin2_code": "",
                "admin3_code": "",
                "admin4_code": "",
                "population": 9056010,
                "elevation": 0,
                "gtopo30": 334,
                "timezone": "Africa/Porto-Novo",
                "modification_date": "02/01/2016"
            },
            {
                "id": 22,
                "geoname_id": 3923057,
                "name": "Bolivia",
                "ascii_name": "Plurinational State of Bolivia",
                "alternate_names": "An Bholaiv,Balivia,Bholiviya,Bo-li-vi-a,Bo-li-vi-a (Bolivia),Boilibhia,Bolibia,Bolibiya,Bolifia,Boliifiya,Boliivia,Bolivaen,Bolivi,Bolivia,Bolivia nutome,Bolivia  Plurinational State Of,Bolivie,Bolivien,Bolivii,Bolivija,Bolivio,Boliviya,Bolivië,Bolivja,Bolivtlan,Bolivtlān,Bolivya,Bolivän,Bolivïi,Boliwia,Boliwii,Bolívia,Bolívie,Bolîvya,Bolīvija,Boribiya,Bulibiya,Bólivía,Bô-li-vi-a,Bô-li-vi-a (Bolivia),Estado Plurinacional de Bolivia,Mbolivi,Orileede Bolifiya,Orílẹ́ède Bọ̀lífíyà,Plurinational State of Bolivia,Polivia,Polīvia,Puliwya,Republic of Bolivia,Republica de Bolivia,República de Bolivia,República de Bolívia,Wuliwya,balgeriya,balibhiya,bealiviya,bo li wei ya,bolabhi'a,bolibhiya,bolivhiya,bolivia,boliviya,boliweiy,bollibia,boribia,boribia gong he guo,bwlybyh,bwlyfya,bwlywy,bwlywya,i-Bolivia,poliviya,prathes boliweiy,Βολιβία,Балівія,Боливия,Боливија,Болівія,Բոլիվիա,בוליביה,بولىۋىيە,بوليفيا,بولیوی,بولیویا,بۆلیڤیا,बोलिभिया,बोलिविया,बोलिव्हिया,बोलीविया,বলিভিয়া,বোলিভিয়া,બોલિવિયા,ବୋଲଭିଆ,பொலிவியா,బొలీవియా,ಬಲ್ಗೇರಿಯಾ,ബൊളീവിയ,බොලීවියාව,ประเทศโบลิเวีย,โบลิเวีย,ໂບລິເວຍ,བོ་ལི་ཝིཡ།,ဘိုလီးဘီးယား,ბოლივია,ቦሊቪያ,បូលីវី,ボリビア,ボリビア共和国,玻利維亞,玻利维亚,볼리비아",
                "latitude": -17,
                "longitude": -65,
                "feature_class": "A",
                "feature_code": "PCLI",
                "country_code": "BO",
                "cc2": "",
                "admin1_code": "00",
                "admin2_code": "",
                "admin3_code": "",
                "admin4_code": "",
                "population": 9947418,
                "elevation": 0,
                "gtopo30": 233,
                "timezone": "America/La_Paz",
                "modification_date": "02/01/2016"
            },
            {
                "id": 12,
                "geoname_id": 3277605,
                "name": "Bosnia and Herzegovina",
                "ascii_name": "Bosnia and Herzegovina",
                "alternate_names": "An Bhoisnia agus Heirseagovein,An Bhoisnia agus Heirseagóvéin,An Bhoisnia-Heirseagaivein,An Bhoisnia-Heirseagaivéin,Bhosnia le Herzegovina,Bo-xni-a Hec-xe-go-vi-na,Bo-xni-a Hec-xe-go-vi-na (Bosnia va Herzegovina),Boosniyaa fi Herzegoviinaa,Bos'nija i Gercagavina,Bosenia me Hesegowina,Bosini mpe Hezegovine,Bosini mpé Hezegovine,Bosiniya na Herigozevine,Bosiniya na Herizegovina,Bosmudin boln Khercegudin Orn,Bosna,Bosna Hersek,Bosna a Hercegovina,Bosna a Hercegowina,Bosna agus Hearsagobhana,Bosna doo Hetsog Bikeyah,Bosna dóó Hetsog Bikéyah,Bosna i Hercegovina,Bosna i Khercegovina,Bosna in Hercegovina,Bosna kap Hercegovina,Bosna u Hersek,Bosna va Hercegovina,Bosna ve Hersek,Bosna và Hercegovina,Bosna-Gercegovina,Bosna-Hersek,Bosnaen e Haerzegovaen,Bosneja i Hercegovina,Bosneje er Hercuogovena,Bosni,Bosni a,Bosni aemae Gercegovinae,Bosni ak Erzegovin,Bosni ba Gercegovina,Bosni ba Khercegovina,Bosni tata Gercegovina,Bosnia,Bosnia & Herzegovina,Bosnia - Erzegobine,Bosnia - Hercegovina - Bosna i Khercegovina,Bosnia - Hercegovina - Босна и Херцеговина,Bosnia Ercegovina,Bosnia Erzegovina,Bosnia Herzegovina,Bosnia Herzogovina,Bosnia Hèrzègovina,Bosnia a Herzegovina,Bosnia aamma Herzegovina,Bosnia and Hercegovina,Bosnia and Herzegofina,Bosnia and Herzegovina,Bosnia as Herzegovina,Bosnia at Herzegovina,Bosnia ati Herjegofina,Bosnia dan Herzegovina,Bosnia e Ercegovina,Bosnia e Erzegovina,Bosnia e Erzegòvina,Bosnia e Hercegovina,Bosnia e Hertsegovina,Bosnia e Herzegovina,Bosnia ed Erzegovina,Bosnia et Herzegovina,Bosnia ev Hercʻegovina,Bosnia gaeng Herzegovina,Bosnia gâe̤ng Herzegovina,Bosnia ha Herzegovina,Bosnia i Gercagavina,Bosnia i Gercogovina,Bosnia i Hercegovina,Bosnia i Hercegowina,Bosnia i Hersegovina,Bosnia ihuan Hertzegovina,Bosnia ja Hercegovina,Bosnia ja Hertsegoviina,Bosnia ja Hertsegovina,Bosnia ja Herzegovina,Bosnia jeung Herzegovina,Bosnia jeung Hérzégovina,Bosnia kai Erzegobine,Bosnia ken Herzegovina,Bosnia kple Herzergovina nutome,Bosnia lan Hercegovina,Bosnia lan Hércegovina,Bosnia lau Herzegovina,Bosnia lâu Herzegovina,Bosnia ma Herzegovina,Bosnia na Erzegovina,Bosnia na Herzegovina,Bosnia na Hesegovina,Bosnia na Hezegovina,Bosnia ne Hɛzegovina,Bosnia og Hercegovina,Bosnia og Hersegovina,Bosnia si Hertegovina,Bosnia sy Herzegovina,Bosnia ta Gercogovina,Bosnia tan Hersegobina,Bosnia ug Herzegovina,Bosnia y Hercegovina,Bosnia y Herzegovina,Bosnia è Erzegovina,Bosnia și Herțegovina,Bosnia-Ercegovina,Bosnia-Erzegovina,Bosnia-Hercegovina,Bosnia-Hersegovina,Bosnia-Hertsegofina,Bosnia-Hertsegovina,Bosnia-Herzegovina,Bosnia-ha-Herzegovina,Bosnie Herzegovina,Bosnie an Herzegovinae,Bosnie en Herzegovina,Bosnie en Herzegowina,Bosnie-Erzegovine,Bosnie-Hercegovina,Bosnie-Herzegovena,Bosnie-Herzegovina,Bosnie-Herzegovine,Bosnie-Herzegowina,Bosnie-Herzégovine,Bosnie-Hèrzègovena,Bosnie-Érzégovine,Bosniehreh Gercegovinehreh,Bosnien an Herzegowina,Bosnien och Hercegovina,Bosnien un Herzegowina,Bosnien und Herzegowina,Bosnien-Hercegovina,Bosnien-Herzegovina,Bosnien-Herzegowina,Bosnii Hersegowiin,Bosnii da Gercegovin,Bosnii na Herzegovinni,Bosnij da Gercegovina,Bosnija,Bosnija bla Gercegovina,Bosnija da Gercegovina,Bosnija di Khercegovina,Bosnija dy Gercegovina Mastor,Bosnija i Gercegovina,Bosnija ir Hercegovina,Bosnija no Gercegovina,Bosnija un Hercegovina,Bosnija uonna Khercegovina,Bosnija va Gercegovina,Bosnija zhana Gercegovina,Bosnijo e Hercegowina,Bosnikondre,Bosnio kaj Hercegovino,Bosnio-Hercegovino,Bosniska a Hercegowina,Bosniska-Hercegowinska,Bosniya,Bosniya Harzagobina,Bosniya Hersigoviina,Bosniya ham Gertsegovina,Bosniya hem Hertegovina,Bosniya hem Herțegovina,Bosniya u Herzegovina,Bosniya va Gersegovina,Bosniya və Herseqovina,Bosniya və Herzokovina,Bosniya we Gersegowina,Bosniya û Herzegovîna,Bosnië Herzegovina,Bosnië en Herzegovina,Bosnië en Herzegowina,Bosnië-Hercegovina,Bosnië-Herzegovina,Bosnië-Herzegowina,Bosniýa we Gersegowina,Bosni–Hercegovina,Bosnja dhe Hercegovina,Bosnje,Bosnya a Hersegowina,Bosnya asin Hersegobina,Bosnya ngan Hersegovina,Bosnän e Härzegovän,Bosnía og Hersegóvína,Bosnïi na Herzegovînni,Bosnėjė ėr Hercuogovėna,Bosznia es Hercegovina,Bosznia és Hercegovina,Bosznia-Hercegovina,Boteniya me Erdegobina,Boziniya Hezegovina,Bozni-Ɛrizigovini,Boznia ne Herzegovina,Boznia no Erzegovina,Boznija Herzegovina,Boznija u Herzegovina,Bośnia i Hercegowina,Bośńa a Hercegowina,Bożnija u Ħerżegovina,Bożnija Ħerżegovina,Busna-Hirsiquwina,Busnya ed Hirziguvina,Bòsnia Erzegovina,Bòsnia e Ercegovina,Bòsnia e Erzegòvina,Bòsnia i Hercegovina,Bòsnia-Erçegòvina,Bòsnijô ë Hercegòwina,Bósnia Ercegovina,Bósnia e Herzegovina,Bósnia-Herzegóvina,Bósníà àti Hẹrjẹgòfínà,Bóznia no Erzegovina,Bô-xni-a Héc-xê-gô-vi-na,Bô-xni-a Héc-xê-gô-vi-na (Bosnia và Herzegovina),IBhosinya ne Hezegovi,IBhosniya neHerzegovina,Mbosini ne Hezegovine,Narodna Republika Bosna i Hercegovina,Orileede Bosinia ati Etisegofina,Orílẹ́ède Bọ̀síníà àti Ẹtisẹgófínà,People's Republic of Bosnia and Hercegovina,People’s Republic of Bosnia and Hercegovina",
                "latitude": 44.25,
                "longitude": 17.83333,
                "feature_class": "A",
                "feature_code": "PCLI",
                "country_code": "BA",
                "cc2": "",
                "admin1_code": "00",
                "admin2_code": "",
                "admin3_code": "",
                "admin4_code": "",
                "population": 4590000,
                "elevation": 0,
                "gtopo30": 876,
                "timezone": "Europe/Sarajevo",
                "modification_date": "06/05/2016"
            },
            {
                "id": 26,
                "geoname_id": 933860,
                "name": "Botswana",
                "ascii_name": "Republic of Botswana",
                "alternate_names": "An Bhotsuain,An Bhotsuáin,Baswana,Batsvana,Bechuanaland Protectorate,Betschuanaland Protektorat,Betsjoeanaland,Betsjoeanaland Protektoraat,Bocuana,Bocvana,Bocvano,Bot-xoa-na,Bot-xoa-na (Botswana),Botiswana,Botsoana,Botsouana,Botsuana,Botsvana,Botsvana Cumhuriyeti,Botsvāna,Botswaana,Botswana,Botswana nutome,Botsƿana,Botuswaana,Botwana,British Protectorate of Bechuanaland,Britse Protektoraat van Betsjoeanaland,Bɔtisiwana,Bɔtswana,Bốt-xoa-na,Bốt-xoa-na (Botswana),IButswana,Mbotswana,Mpotsouana,Northern Bechuanaland,Orileede Botisuwana,Orílẹ́ède Bọ̀tìsúwánà,Potisiuana,Republic of Botswana,Republica de Botsuana,Republica de Botswana,República de Botsuana,República de Botswana,Zvanaen,Zvanän,batasoyana,beatsvana,bo ci wa na,bo zha na,bocheuwana,botasban,botsavana,botsuwana,botsuwana gong he guo,botsvana,btswana,bwtsvana,bwtswana,bxt swa na,i-Botswana,potsvana,pra thes bxt swa na,Μποτσουάνα,Батсвана,Ботсвана,Ботсуана,Боцвана,Բոտսվանա,בוטסואנה,בוטסוואנה,بتسوانا,بوتسوانا,بوتسۋانا,بۆتسوانا,बोट्सवाना,बोट्स्वाना,बोत्सवाना,बोत्स्वाना,বতসোয়ানা,বোত্‍সওয়ানা,બોત્સ્વાના,ବୋଟସ୍ବାନ୍,போட்ஸ்வானா,బోట్స్వానా,ಬೋಟ್ಸ್‌ವಾನಾ,ബോട്സ്വാന,බොස්ට්වානා,บอตสวานา,ประเทศบอตสวานา,ບອັດສະວານາ,བོཙ་ཝ་ན།,ဘော့စ်ဝါနာ,ბოტსვანა,ቦትስዋና,បុតស្វាណា,ボツワナ,ボツワナ共和国,博茨瓦纳,波札那,보츠와나",
                "latitude": -22,
                "longitude": 24,
                "feature_class": "A",
                "feature_code": "PCLI",
                "country_code": "BW",
                "cc2": "",
                "admin1_code": "00",
                "admin2_code": "",
                "admin3_code": "",
                "admin4_code": "",
                "population": 2029307,
                "elevation": 0,
                "gtopo30": 963,
                "timezone": "Africa/Gaborone",
                "modification_date": "10/17/2014"
            },
            {
                "id": 23,
                "geoname_id": 3469034,
                "name": "Brasil",
                "ascii_name": "Federative Republic of Brazil",
                "alternate_names": "An Bhrasail,An Bhrasaíl,Ba Tay (Bra-xin),Ba Tây (Bra-xin),Baraasiil,Beresiil,Berezili,Birazil,Bra-xin,Braasiil,Brasiilia,Brasil,Brasila,Brasilaen,Brasile,Brasili,Brasilia,Brasilie,Brasilien,Brasilië,Brasilän,Brasilía,Brasíle,Brasīl,Braxil,Braziel,Braziilii,Brazil,Brazil nutome,Brazili,Brazilia,Brazilie,Brazilija,Braziliya,Brazilië,Brazilo,Brazylia,Brazylje,Brazíl,Brazília,Brazílie,Brazīlija,Brażil,Breasail,Bresi,Bresil,Brezil,Brezila,Brezili,Brezilya,Brezílɛ,Brezîli,Brèsil,Brési,Brésil,Buraziiri,Burezili,Estados Unidos do Brasil,Estados Unidos do Brazil,Federative Republic of Brazil,Mnulezile,Orileede Barasili,Orílẹ́ède Bàràsílì,Palakila,Palasili,Palāsili,Republica Federativa do Brasil,Republica dos Estados Unidos do Brasil,República Federativa do Brasil,República dos Estados Unidos do Brasil,United States of Brazil,albrazyl,ba xi,beulajil,braajila,brajhila,brajil,brajila,brasil,brasila,brazila,brazilia,brazyl,brazyly,brejil,brzyl,burajiru,burajiru lian bang gong he guo,i-Brazil,pirecil,piresil,prathes brasil,razgu'e,Βραζιλία,Бразил,Бразили,Бразилия,Бразилія,Бразілія,Браѕил,Բրազիլիա,בראזיליע,ברזיל,البرازيل,برازىلىيە,برازيل,برازیل,برازیلی,برزیل,ब्राज़िल,ब्राजिल,ब्राजील,ब्राझिल,ब्रास़ील,ব্রাজিল,ব্ৰাজিল,બ્રાઝિલ,ବ୍ରାଜିଲ୍,பிரேசில்,பிரேஸில்,బ్రజిల్,ಬ್ರೆಜಿಲ್,ബ്രസീല്‍,බ්‍රසීලය,บราซิล,ประเทศบราซิล,ບຼາຊິວ,པུ་རུ་ཟིལ,བ་རཱ་ཛིལ།,བཱརཱ་ཛིལ,ဘရာဇီး,ბრაზილია,ብራዚል,ប្រេស៊ីល,ブラジル,ブラジル連邦共和国,巴西,ꀠꑭ,브라질",
                "latitude": -10,
                "longitude": -55,
                "feature_class": "A",
                "feature_code": "PCLI",
                "country_code": "BR",
                "cc2": "",
                "admin1_code": "00",
                "admin2_code": "",
                "admin3_code": "",
                "admin4_code": "",
                "population": 201103330,
                "elevation": 0,
                "gtopo30": 258,
                "timezone": "",
                "modification_date": "10/07/2015"
            },
            {
                "id": 21,
                "geoname_id": 1820814,
                "name": "Brunei",
                "ascii_name": "Brunei Darussalam",
                "alternate_names": "Brineyi,Broenai,Broenei,Brouney,Bru-nay,Bru-nây,Bruine,Brunae,Brunaen,Brunaigh,Brunay,Brunei,Brunei Darussalam,Brunei nutome,Bruneium,Brunej,Brunej Darusalam,Brunej Darussalam,Brunej-Darusalam,Brunej-Darussalam,Bruneja,Brunejo,Brunejus,Bruney,Bruneyi,Brunän,Brunéi,Brunéi Darussalam,Brunêi,Brunėjus,Brùnaigh,Brúiné,Brúnei,Brûnei,Brûney,Burinɛyi,Burnaay,Burunayi,Burune,Buruneeya,Burunei,Buruneyi,Mprounei,Mprounei Ntarousalam,Negara Brunei Darussalam,Negeri Brunei,Orileede Buruneli,Orílẹ́ède Búrúnẹ́lì,Pulunei,State of Brunei,Sultanate of Brunei,beulunai,bruna'i,brunai,brune'i,brunei,bruni,brwnay,brwny,brwnyy,brwwnay,burunei,i-Brunei,prathes bruni,puruney,wen lai,Μπρουνέι,Μπρουνέι Νταρουσαλάμ,Брунеи,Бруней,Бруней Дарусалам,Бруней Даруссалам,Бруней-Дарусалам,Бруней-Даруссалам,Брунеј,Բրունեյ,ברוניי,ברוניי דארוסאלאם,برونئی,بروناي,برونای,بروني,بروونای,برۇنېي,ब्रुनाइ,ब्रुनेई,ब्रूनइ,ब्रूनै,ব্রুনাই,ব্রুনেই,બ્રુનેઇ,ବ୍ରୁନେଇ,புரூனேய்,బ్రునై,ಬ್ರೂನಿ,ബ്രൂണൈ,බෲනායි,บรูไน,ประเทศบรูไน,ບູຮໄນ,བུ་རུ་ནེ།,ဘရူနိုင်း,ბრუნეი,ብሩኒ,ប៊្រុយណេ,ブルネイ,文莱,브루나이",
                "latitude": 4.5,
                "longitude": 114.66667,
                "feature_class": "A",
                "feature_code": "PCLI",
                "country_code": "BN",
                "cc2": "",
                "admin1_code": "00",
                "admin2_code": "",
                "admin3_code": "",
                "admin4_code": "",
                "population": 395027,
                "elevation": 0,
                "gtopo30": 95,
                "timezone": "Asia/Brunei",
                "modification_date": "02/01/2016"
            },
            {
                "id": 16,
                "geoname_id": 2361809,
                "name": "Burkina Faso",
                "ascii_name": "Burkina Faso",
                "alternate_names": "Bhukina Faso,Boerkina Faso,Boerkina Fasso,Borkena Fasos,Borkina Faso,Borkinn-a Faeso,Borkinn-a Fäso,Borkėna Fasos,Boukinafaso,Buircine Faso,Buirciona Faso,Buircíne Fasó,Bukina Faso,Bukinafaso,Buoc-ki-na Pha-xo,Buoc-ki-na Pha-xo (Burkina Faso),Burakina Faso,Burchina Fasu,Burcina Faso,Burkibaa Faaso,Burkiina Faaso,Burkina,Burkina Fasas,Burkina Faso,Burkina Faso nutome,Burkina Fasso,Burkina Fasso (Alto Volta),Burkina Fasu,Burkina Fasô,Burkina Paso,Burkina Phasu,Burkina faso,Burkina-Faso,Burkinaa Faaso,Burkinaa Faasoo,Burkinabato,Burkinaen,Burkinafaso,Burkinapasin Orn,Burkino,Burkino-Faso,Burkinän,Burkína Fasó,Burkîna Faso,Burquina Faso,Burquina Fasu,Burukina Faso,Buốc-ki-na Pha-xô,Buốc-ki-na Pha-xô (Burkina Faso),Bwrcina Ffaso,Bùrkínà Fasò,Búrkína Fasó,Bɔkina Faso,IBhukhina-Faso,IBukhina Faso,Mpourkina Phaso,Orileede Buukina Faso,Orílẹ́ède Bùùkíná Fasò,Pekano Faso,Republic of Upper Volta,Republique Voltaique,Republique de Haute-Volta,République Voltaïque,République de Haute-Volta,Volta Republic,Volta Superior,Voltaic Republic,barkina phaso,brkyna fasw,bu ji na fa suo,buleukina paso,buleukinapaso,bur kin afa so,burakina faso,burakina phaso,burkina faso,burkina phaso,burkina-phaso,burkino phaso,burukina faso,burukinafaso,bwrkyna fasw,bwrkynafasw,i-Burkina Faso,pra thes bur kin afa so,purkina hpaso,purkkina paco,Μπουρκίνα Φάσο,Буркина Фасо,Буркина-Фасо,Буркинапасин Орн,Буркино-Фасо,Буркіна Фасо,Буркіна-Фасо,Բուրկինա Ֆասո,בורקינה פאסו,בורקינע פאסא,برکینا فاسو,بوركينا فاسو,بورکینا فاسو,بورکینافاسو,بورکینافاسۆ,بۇركىنا فاسو,ބުރުކީނާ ފާސޯ,बर्किना फासो,बुर्किना फ़ासो,बुर्किना फासो,बुर्कीना-फासो,বুরকিনা ফাসো,বুর্কিনা ফাসো,ਬੁਰਕੀਨਾ ਫ਼ਾਸੋ,બુર્કિના ફાસો,ବୁରକିନା ଫାସୋ,ବୁର୍କିନୋ ଫାସୋ,புர்கினா ஃபாஸோ,புர்க்கினா பாசோ,బర్కీనా ఫాసో,బుర్కినా ఫాసో,ಬುರ್ಕಿನಾ ಫಾಸೋ,ಬುರ್ಕೀನ ಫಾಸೊ,ബുര്‍ക്കിനാ ഫാസോ,ബർക്കിനാ ഫാസോ,බර්කිනා ෆාසෝ,บูร์กินาฟาโซ,ประเทศบูร์กินาฟาโซ,ເບີກິນາຟາໂຊ,བརཀི་ན། ཕསོ།,བུར་ཀི་ན་ཕ་སོ།,ဘာကီးနားဖားဆိုနိုင်ငံ,ბურკინა ფასო,ბურკინა-ფასო,ቡርኪና ፋሶ,ប៊ូរគីណាហ្វាសូ,ブルキナファソ,布吉納法索,布基納法索,布基纳法索,부르키나 파소,부르키나파소",
                "latitude": 12.5,
                "longitude": -1.66667,
                "feature_class": "A",
                "feature_code": "PCLI",
                "country_code": "BF",
                "cc2": "",
                "admin1_code": "00",
                "admin2_code": "",
                "admin3_code": "",
                "admin4_code": "",
                "population": 16241811,
                "elevation": 0,
                "gtopo30": 313,
                "timezone": "Africa/Ouagadougou",
                "modification_date": "11/09/2013"
            },
            {
                "id": 19,
                "geoname_id": 433561,
                "name": "Burundi",
                "ascii_name": "Republic of Burundi",
                "alternate_names": "An Bhuruin,An Bhurúin,Bhurundi,Boeroendi,Boerundy,Boerûndy,Borondi,Bouroundi,Bu-run-gi,Bu-run-gi (Burundi),Bu-run-đi,Bu-run-đi (Burundi),Burundaidh,Burundee,Burundi,Burundi nutome,Burundia,Burundii,Burundin Orn,Burundis,Burundo,Burundzi,Burundî,Burundïi,Burunndi,Buruundi,Burůndi,Bwrwndi,Bùrúndì,Búrúndí,IBurundi,Mburundi,Mpourounti,Orileede Buurundi,Orílẹ́ède Bùùrúndì,Pelaniti,Republic of Burundi,Republica de Burundi,Republika y'u Burundi,Republika y’u Burundi,Republique du Burundi,República de Burundi,Rundiyaen,Rundiyän,République du Burundi,Uburundi,Urundi,Wóndii Dineʼé Bikéyah,barandi,barunti,brwndy,bu long di,bulundi,burundi,burunji,burunji gong he guo,burunti,bwrandy,bwrwndy,i-Burundi,prathes burundi,pu long de,purunti,Μπουρούντι,Бурундзі,Бурунди,Бурундин Орн,Бурунді,Բուրունդի,בורונדי,برنڈی,بروندي,برونڈی,بوراندی,بوروندى,بوروندي,بوروندی,بۇرۇندى,ބުރުންޑީ,बरंडी,बुरुंडी,बुरुण्डी,बुरुन्डी,बुरूण्डी,বুরুণ্ডি,বুরুন্ডি,બુરુંડી,ବୁରୁନ୍ଦି,புருண்டி,బురుండి,ಬುರುಂಡಿ,ബറുണ്ടി,ബുറുണ്ടി,බුරුන්ඩි,บุรุนดี,ประเทศบุรุนดี,ບູລັນຕິ,བུ་རུན་ཌི།,ბურუნდი,ቡሩንዲ,ብሩንዲ,ប៊ូរុនឌី,ブルンジ,ブルンジ共和国,布隆迪,蒲隆地,부룬디",
                "latitude": -3.5,
                "longitude": 30,
                "feature_class": "A",
                "feature_code": "PCLI",
                "country_code": "BI",
                "cc2": "",
                "admin1_code": "00",
                "admin2_code": "",
                "admin3_code": "",
                "admin4_code": "",
                "population": 9863117,
                "elevation": 0,
                "gtopo30": 1732,
                "timezone": "Africa/Bujumbura",
                "modification_date": "03/06/2013"
            },
            {
                "id": 41,
                "geoname_id": 3374766,
                "name": "Cabo Verde",
                "ascii_name": "Republic of Cabo Verde",
                "alternate_names": "An Rinn Ghlas,Azua ti Kapo-Vere,Azûâ tî Kâpo-Vêre,Bisanga bya Kapevɛrɛ,Bizinga by'e Kepu Veredi,Cabo Verde,Cap Verd,Cap Verde,Cap-Vert,Cap-ve,Cape Verde,Cape Verde Islands,Capivɛrdi,Capo Verde,Capul Verde,Cáp-ve,Duuɗe Kap Weer,Graenhoefdaeyjar,Gronhovdaoyggjarnar,Grænhöfðaeyjar,Grønhøvdaoyggjarnar,Ibirwa bya Kapuveri,Kaap Verde,Kaapverdie,Kaapverdië,Kab Glas,Kaba-Verdeh,Kabo Verde,Kabo-Verde,Kabo-Verdo,Kaboverde,Kap Verde,Kape Verde,Kape Verde nutome,Kapp Verde,Kapverden,Kapverdische Inseln,Kapverdy,Kepuvede,Kepvɛdfo Islands,Lutanda lua Kapevele,Mui'i Veti,Muiʻi Veti,Nosy Cap-Vert,Orileede Etiokun Kape fende,Orílẹ́ède Etíokun Kápé féndè,Ostrova Zelenogo Mysa,Prasino Akrotirio,Province of Cape Verde,Provincia de Cabo Verde,Província de Cabo Verde,Republic of Cabo Verde,Republic of Cape Verde,Republic of Cape Verde Islands,Republica de Cabo Verde,Republika Zielonego Przyladka,Republika Zielonego Przylądka,República de Cabo Verde,Roheneemesaared,Tanjung Verde,Tsibiran Kap Barde,Yesilburun,Yeşilburun,Zaliasis Kysulys,Zeleni Rt,Zelenortski Ostrovi,Zelenortski otoki,Zoeld-foki Koeztarsasag,Zvitsuwa zveCape Verde,Zöld-foki Köztársaság,alras alakhdr,fu de jiao,i-Cape Verde,kabobeleude,kaboberude,kaipa varde,kaipa varta,kep bharde,kep varde,kep verde,kep verte,kepa bharde,kepa varde,kepa vharde,kepabharde,khep weird,kp wrdh,Žaliasis Kyšulys,Πράσινο Ακρωτήριο,Зеленортски Острови,Каба-Вердэ,Кабо Верде,Кабо-Верде,Капе Верде,Острова Зеленого Мыса,Կաբո-Վերդե,כף ורדה,קאפ ורדה,الرأس الأخضر,الرأس الاخضر,کیپ ورڈی,کیپ‌ورد,کەیپڤەرد,केप भर्डे,केप व्हर्डे,कैप वर्डे,कैप वर्त,কেপভার্দে,કૅપ વર્ડે,କେପ୍ ଭର୍ଦେ,கேப் வெர்டே,కేప్ వెర్డే,ಕೇಪ್ ವರ್ಡೆ,കേപ്പ് വെര്‍ഡെ,เคปเวิร์ด,ເຄບວອດ,კაბო-ვერდე,ኬፕ ቬርዴ,កាបវែរ,カーボベルデ,佛得角,카보베르데",
                "latitude": 16,
                "longitude": -24,
                "feature_class": "A",
                "feature_code": "PCLI",
                "country_code": "CV",
                "cc2": "",
                "admin1_code": "00",
                "admin2_code": "",
                "admin3_code": "",
                "admin4_code": "",
                "population": 508659,
                "elevation": 0,
                "gtopo30": -9999,
                "timezone": "Atlantic/Cape_Verde",
                "modification_date": "11/25/2016"
            },
            {
                "id": 36,
                "geoname_id": 2233387,
                "name": "Cameroon",
                "ascii_name": "Republic of Cameroon",
                "alternate_names": "Ca-mo-run,Ca-mo-run (Cameroon),Ca-mơ-run,Ca-mơ-run (Cameroon),Camaroes,Camarun,Camarões,Camarún,Cameron,Cameronia,Cameroon,Cameroun,Camerun,Camerun - Cameroun,Camerwn,Camerún,Camerún - Cameroun,Camerŵn,Federal Republic of Cameroon,Federation of the Camerouns,Kaameruun,Kamaru,Kameroen,Kamerona,Kameroun,Kamerun,Kamerun nutome,Kameruna,Kamerunaen,Kamerunas,Kamerune,Kameruni,Kameruno,Kamerunän,Kameruun,Kameruuni,Kamerún,Kamerûn,Kamerûne,Kamerūna,Kamerūnas,Kamɛrun,Kamɛrune,Kemaluni,Khameruni,Orileede Kameruuni,Orílẹ́ède Kamerúúnì,Republic of Cameroon,Republica dos Camaroes,Republique Federale du Cameroun,Republique Unie du Cameroun,Republique du Cameroun,República dos Camarões,République Fédérale du Cameroun,République Unie du Cameroun,République du Cameroun,United Republic of Cameroon,Y Camerwn,Y Camerŵn,alkamyrwn,i-Cameroon,kaimaruna,kamelun,kamerana,kamerun,kamerun gong he guo,kameruna,kamrwn,kamyrwn,kamyrwwn,ke mai long,kemarun,kemaruna,kemeruna,kyamaron,kyamarun,kyameruna,kymrwn,qmrwn,Καμερούν,Камерун,Կամերուն,קאמרון,קמרון,الكاميرون,كاميرون,كامېرون,کامرون,کامیروون,کیمرون,کېمرون,कामेरान,कामेरून,कॅमेरून,केमेरून,कैमरून,क्यामेरून,ক্যামেরুন,કૅમરૂન,କାମେରୁନ୍,கேமரூன்,కెమరూన్,ಕ್ಯಾಮರೂನ್,ಕ್ಯಾಮರೋನ್,കാമറൂണ്‍,කැමරූන්,ประเทศแคเมอรูน,แคเมอรูน,ຄາເມລູນ,ཀ་མེ་རུན།,ကင်မရွန်း,კამერუნი,ካሜሩን,កាមេរូន,カメルーン,カメルーン共和国,喀麦隆,카메룬",
                "latitude": 6,
                "longitude": 12.5,
                "feature_class": "A",
                "feature_code": "PCLI",
                "country_code": "CM",
                "cc2": "",
                "admin1_code": "00",
                "admin2_code": "",
                "admin3_code": "",
                "admin4_code": "",
                "population": 19294149,
                "elevation": 0,
                "gtopo30": 720,
                "timezone": "Africa/Douala",
                "modification_date": "11/07/2013"
            },
            {
                "id": 29,
                "geoname_id": 6251999,
                "name": "Canada",
                "ascii_name": "Canada",
                "alternate_names": "Ca-na-da,Ca-na-đa,Canada,Canada (Gia Na GJai),Canada (Gia Nã Đại),Canadà,Canadá,Ceanada,Kanada,Kanada nutome,Kanadaa,Kanadaea,Kanadas,Kanado,Kanadäa,Kanata,Kanuadu,Kanáda,Kanāda,Khanada,Kānata,Orileede Kanada,Orílẹ́ède Kánádà,i-Canada,jia na da,kaenada,kanada,kanata,kenada,keneda,knda,kyanada,qndh,Καναδάς,Канада,Կանադա,קנדה,كندا,کانادا,کاناډا,کانەدا,کینیڈا,कनाडा,कॅनडा,क्यानाडा,কানাডা,કેનેડા,କାନାଡା,கனடா,కెనడా,ಕೆನಡಾ,കാനഡ,කැනඩාව,แคนาดา,ການາດາ,ཀེ་ན་ཌ,ཁེ་ན་ཌ།,ကနေဒါ,კანადა,ካናዳ,កាណាដា,カナダ,加拿大,캐나다",
                "latitude": 60.10867,
                "longitude": -113.64258,
                "feature_class": "A",
                "feature_code": "PCLI",
                "country_code": "CA",
                "cc2": "",
                "admin1_code": "00",
                "admin2_code": "",
                "admin3_code": "",
                "admin4_code": "",
                "population": 33679000,
                "elevation": 0,
                "gtopo30": 292,
                "timezone": "",
                "modification_date": "10/07/2015"
            },
            {
                "id": 35,
                "geoname_id": 3895114,
                "name": "Chile",
                "ascii_name": "Republic of Chile",
                "alternate_names": "An t-Sile,An tSile,Cayile,Chi-le,Chi-le (Chile),Chi-lê,Chi-lê (Chile),Chiilii,Chile,Chili,Chilia,Chilmudin Orn,Chilska,Chu-li,Ch·ili,Chíilii,Chíle,Chṳ-li,Ciile,Cilaen,Cile,Cili,Cilii,Cilio,Cilän,Cilé,Ciłe,Csile,Cyli,Czile,Jili,Kili,Kyili,Orileede sile,Orílẹ́ède ṣílè,Republic of Chile,Republica de Chile,República de Chile,Shiile,Shili,Shilii,Shilïi,Sile,Sili,Sily,Síli,Tchili,Tiiili,Tsiili,Tsile,Tsile nutome,Tsire,Tsílè,Txile,Tšiili,Xile,Yn Chillee,Yn Çhillee,chile,chili,chille,chiri,chiri gong he guo,chly,chyly,cile,cili,cilli,i-Chile,prathes chili,shyly,tciles,tshyly,zhi li,zylh,Çile,Çili,Ĉilio,Ċili,Čiile,Čile,Čilė,Čīle,Şili,Şîle,Χιλή,Чиле,Чили,Чилмудин Орн,Чилі,Чылі,Чілі,Չիլի,טשילע,צילה,צ׳ילה,تشيلى,تشيلي,شيلي,شیلی,چلي,چلی,چىلى,چېلي,ޗިލީ,चिलि,चिली,चिले,চিলি,ચિલી,ચીલી,ଚିଲ୍ଲୀ,சிலி,చిలి,చిలీ,ಚಿಲಿ,ചിലി,චිලි ජනරජය,චිලී,ชิลี,ประเทศชิลี,ຊິສິ,ཅི་ལི་སྤྱི་མཐུན་རྒྱལ་ཁབ།,ཅི་ལི།,ချီလီ,ချီလီပြည်သူ့သမ္မတနိုင်ငံ,ჩილე,ჩილი,ቺሊ,ቺሌ,ឈីលី,チリ,チリ共和国,智利,칠레",
                "latitude": -30,
                "longitude": -71,
                "feature_class": "A",
                "feature_code": "PCLI",
                "country_code": "CL",
                "cc2": "",
                "admin1_code": "00",
                "admin2_code": "",
                "admin3_code": "",
                "admin4_code": "",
                "population": 16746491,
                "elevation": 0,
                "gtopo30": 297,
                "timezone": "",
                "modification_date": "03/05/2013"
            },
            {
                "id": 38,
                "geoname_id": 3686110,
                "name": "Colombia",
                "ascii_name": "Republic of Colombia",
                "alternate_names": "An Choloim,An Cholóim,Co-lom-bi-a,Co-lom-bi-a (Colombia),Coloimbia,Colombia,Colombie,Colombié,Columbia,Columbien,Colòmbia,Colómbia,Colômbia,Cô-lôm-bi-a,Cô-lôm-bi-a (Colombia),Kalumbia,Kholombiya,Kolambiya,Kolombi,Kolombia,Kolombia nutome,Kolombie,Kolombii,Kolombio,Kolombiya,Kolombië,Kolombya,Kolombïi,Kolomipia,Kolonbi,Kolonbia,Kolumbaen,Kolumbi,Kolumbia,Kolumbie,Kolumbien,Kolumbija,Kolumbiya,Kolumbja,Kolumbän,Kolómbia,Korombiya,Kulumbija,Kulumbiya,Kulumbya,Kólumbía,Kôlômbia,Orileede Kolomibia,Orílẹ́ède Kòlómíbìa,Republic of Colombia,Republica de Colombia,República de Colombia,Yn Cholombey,ge lun bi ya,ge lun bi ya gong he guo,i-Colombia,kalambiya,kealambiya,kholambeiy,kholxmbeiy,klmbya,kolambi'a,kolambiya,kolampiya,kollombia,kolombiya,koronbia,koronbia gong he guo,kwlmbya,kwlwmbya,prathes kholxmbeiy,qwlwmbyh,Κολομβία,Калумбія,Колумбия,Колумбија,Колумбія,Кулумбия,Կոլումբիա,קאלאמביע,קולומביה,كولومبىيە,كولومبيا,کلمبیا,کولمبيا,کولمبیا,کۆلۆمبیا,कोलम्बिया,कोलोम्बिया,কলম্বিয়া,কোলোম্বিয়া,কোলোম্বিয়া,કોલમ્બિયા,କୋଲମ୍ବିଆ,கொலம்பியா,కొలంబియా,ಕೊಲಂಬಿಯಾ,കൊളംബിയ,කොළොම්බියාව,ประเทศโคลอมเบีย,โคลอมเบีย,โคลัมเบีย,ໂຄລຳເບຍ,ཀོ་ལོམ་བི་ཡ།,ཁ་ལམ་བ་ཡ།,ཁོ་ལོམ་བི་ཡ།,ကိုလံဘီယာ,კოლუმბია,ኮሎምቢያ,កូឡុំប៊ី,コロンビア,コロンビア共和国,哥伦比亚,哥伦比亚共和国,콜롬비아",
                "latitude": 4,
                "longitude": -73.25,
                "feature_class": "A",
                "feature_code": "PCLI",
                "country_code": "CO",
                "cc2": "",
                "admin1_code": "00",
                "admin2_code": "",
                "admin3_code": "",
                "admin4_code": "",
                "population": 47790000,
                "elevation": 0,
                "gtopo30": 223,
                "timezone": "America/Bogota",
                "modification_date": "09/23/2014"
            },
            {
                "id": 32,
                "geoname_id": 2260494,
                "name": "Congo-Brazzaville",
                "ascii_name": "Republic of the Congo",
                "alternate_names": "An Congo,An Congó,Concu,Cong hoa Congo,Cong-go,Cong-go (Congo),Congo,Congo (Brazzaville),Congo - Brazzaville,Congo [Republica],Congo [Republiek],Congo [República],Congo-Brazzaville,Còngo,Còngo - Brazzaville,Công-gô,Công-gô (Congo),Cộng hoà Congo,Demokratia tou Kon'nko,Jamhuri ya Kongo,Khongo,Kon'nko - Brazavil,Konga,Kongas,Kongo,Kongo (Republik Kongo),Kongo - Brazavil,Kongo - Brazzavil',Kongo - Brazzaville,Kongo - Republik,Kongo Brazavila,Kongo Cumhuriyeti,Kongo Respublika,Kongo Vabariik,Kongo [Koeztarsasag],Kongo [Republik],Kongo [Republika],Kongo repɔblik nutome,Kongo-Brazzaville,Kongoaen,Kongoe,Kongoi Koeztarsasag,Kongoko Errepublika,Kongolo,Kongon tasavalta,Kongoän,Kongu,Kongó,Kongó [Köztársaság],Kongói Köztársaság,Kongö,Konngo,Konqo - Brazavil,Kôngô,Lipapilika Kongo,Middle Congo,Moyen-Congo,Orileede Kongo,Orílẹ́ède Kóngò,Repoblek Kongo,Repubblica del Congo,Repubilika ya Kongo,Republic of the Congo,Republica Congo,Republica d'o Congo,Republica de Congo,Republica de Còngo,Republica del Congo,Republica del Congò,Republica du Congo,Republiek van die Kongo,Republik Congo,Republik Kongo,Republika Konga,Republika Kongo,Republika e Kongos,Republika ng Congo,Republiken Kongo,Republiki ya Kɔ́ngɔ,Republikken Congo,Republikken Kongo,Republiko Kongo,Republique Populaire du Congo,Republique du Congo,República del Congo,Respublica Congensis,Respublika Kongo,Rèpublica du Congô,République Populaire du Congo,République du Congo,Vestur-Kongo,Vestur-Kongó,Y Congo [Gweriniaeth],alkwnghw,alkwnghw - brazafyl,e-Congo [Republic],gang guo,gang guo gong he guo,hrpwblyqh sl qwngw,jmhwry kngw,jmhwryt alkwnghw,kamgo - brajavile,kango,kango-brajibhille,kango[ganarajyam],kanko [kutiyaracu],khxngko-bra s sa wil,kngw [jmhwry],kong-go,kong-go gonghwagug,kongo,kongo - brajhavile,kongo - brajjabhille,kongo gong he guo,kwngw,satharnrath khxngko,Δημοκρατία του Κονγκό,Κονγκό - Μπραζαβίλ,Конга,Конго,Конго - Бразавил,Конґо,Конґо - Браззавіль,Република Конго,Республика Конго,Կոնգո,הרפובליקה של קונגו,קונגו - ברזאויל,الكونغو,الكونغو - برازافيل,جمهورية الكونغو,جمهوری کنگو,د کانګو جمهوريت,كونگو,کانگو [جمہوریہ],کنگو [جمهوری],کۆماری کۆنگۆ,काँगो - ब्राजाविले,कांगो,कोंगो,कोङ्गो - ब्राज्जाभिल्ले,কঙ্গো,કોંગો - બ્રાઝાવિલે,କଙ୍ଗୋ-ବ୍ରାଜିଭିଲ୍ଲେ,காங்கோ [குடியரசு],కాంగో[గణరాజ్యం],ಕಾಂಗೋ [ರಿಪಬ್ಲಿಕ್‌],കോംഗോ - ബ്രാസാവില്‍,කොංගෝව,คองโก-บราซซาวิล,สาธารณรัฐคองโก,ຄອງໂກ,ཀོང་ཀོ,კონგო,ኮንጎ ሪፑብሊክ,ኮንጐ,កុងហ្គោ,コンゴ,コンゴ共和国,刚果,刚果共和国,콩고,콩고 공화국",
                "latitude": -1,
                "longitude": 15.5,
                "feature_class": "A",
                "feature_code": "PCLI",
                "country_code": "CG",
                "cc2": "",
                "admin1_code": "00",
                "admin2_code": "",
                "admin3_code": "",
                "admin4_code": "",
                "population": 3039126,
                "elevation": 0,
                "gtopo30": 396,
                "timezone": "Africa/Brazzaville",
                "modification_date": "09/22/2014"
            },
            {
                "id": 30,
                "geoname_id": 203312,
                "name": "Congo-Kinshasa",
                "ascii_name": "Democratic Republic of the Congo",
                "alternate_names": "Austur-Kongo,Austur-Kongó,Belgian Congo,Belgisch Congo,Belgisch Kongo,Bүgehdeh Najramdakha Aradshalһan Kongo Ulas,Cong hoa Dan chu Congo,Cong-go (DRC),Congo,Congo - Kinshasa,Congo Belge,Congo Bin-chu Kiong-ho-kok,Congo Bîn-chú Kiōng-hô-kok,Congo Democratico,Congo Democrático,Congo Free State,Congo Min-chu Khiung-fo-koet,Congo Ming-cio Geung-huo-guok,Congo Mìn-chú Khiung-fò-koet,Congo Mìng-ciō Gê̤ṳng-huò-guók,Congo [DRC],Congo  Republica Democratica,Congo  Republica Democratică,Congo  The Democratic Republic Of,Congo-Kinchassa,Congo-Kinshasa,Cumhuriyete Kongoye Demokratiki,Cumhuriyetê Kongoyê Demokratiki,Còngo - Kinshasa,Công-gô (DRC),Cộng hòa Dân chủ Congo,DR Congo,Dehmakratychnaja Rehspublika Konga,Democratic Republic de Congo,Democratic Republic o the Congo,Democratic Republic of Congo,Democratic Republic of the Congo,Demokraatsche Republik Kongo,Demokratesch Republik Kongo,Demokrati Republike de Kongo,Demokratia Respubliko Kongo,Demokratial Republiko Kongo,Demokraticheskaja Respublika Kongo,Demokratichna Republika Kongo,Demokratichna Respublika Kongo,Demokratichna republika Kongo,Demokraticka republika Kongo,Demokratická republika Kongo,Demokraticna republika Kongo,Demokraticna respublika Kongo,Demokratiese Republiek van die Kongo,Demokratijadin Respublika Kongo,Demokratik Kongo Cumhuriyeti,Demokratik Repablik o t Kongo,Demokratika Republika ning Kongo,Demokratiko a Republika iti Kongo,Demokratikong Republika kan Kongo,Demokratikong Republika ng Congo,Demokratin Respublika Kongo,Demokratische Republek Kongo,Demokratische Republik Kongo,Demokratiska Republiken Kongo,Demokratiska republika Kongo,Demokratiske Republik Congo,Demokratiske Republik Kongo,Demokratična republika Kongo,Demokratska Republika Kongo,Demokratska republika Kongo,Demokratyczna Republika Konga,Demokratyske Republyk Kongo,Den Demokratiske Republik Congo,Den demokratiske republikken Kongo,Ditunga wa Kongu,Dymokratyczno Republika Kunga,Dymokratyczno Republika Kůnga,Federal Republic of the Congo,Federation of the Congo,Folcricelicu Cynewise thaes Congwes,Folcrīcelicu Cynewīse þæs Congwes,Folkaraediliga Lydveldid Kongo,Fólkaræðiliga Lýðveldið Kongo,Ganggoj Minzcuj Gunghozgoz,Gweriniaeth Ddemocrataidd y Congo,IKhongo,IRiphabliki Labantu weKongo,Jamhuri ya Kidemokrasia ya Kongo,Jamhuriyar Dimokuraɗiyyar Kongo,Jamhuriyar dimokuradiyya Kwango,Jamhuuriyada Dimuqaraadiga Kongo,Jamhuuriyadda Dimuquraadiga Kongo,Koedoeroesese ti Ngunuhalezo ti kongoe,Kon'nko  Demokratia tou,Kon'nko  Laike Demokratia tou,Konga Demokratiskuo Republika,Konga  Demakratycnaa Respublika,Kongo,Kongo (DRK),Kongo (Kinshasa),Kongo (Zair),Kongo - DRK,Kongo - Kinshasa,Kongo - Zayire,Kongo Cumhuriyeti,Kongo DR,Kongo DV,Kongo Demokraatlik Vabariik,Kongo Demokrati Respublika,Kongo Demokratijalyk Respublikasy,Kongo Demokratik Cumhuriyeti,Kongo Demokratik Respublikasi,Kongo Demokratik Respublikasy,Kongo Demokratik Respublikası,Kongo Demokratille Respubliki,Kongo Demokratine Respublika,Kongo Demokratinė Respublika,Kongo Demokratiska Republika,Kongo Demokrātiskā Republika,Kongo Kinshasa nutome,Kongo [DRC],Kongo [DRK],Kongo [Jamhuri ya Kidemokrasia],Kongo [KED],Kongo [RDK],Kongo demokrahtalas dassevaldi,Kongo demokráhtalaš dásseváldi,Kongo ka Bɛjɛfanga Fasojamana,Kongo ka republiki demɔkratiki,Kongo  Demokraticheskaja Respublika,Kongo  Demokraticna Respublika,Kongo  Demokratikus koeztarsasag,Kongo  Demokratska Republika,Kongo  Republika Demokratyczna,Kongo  demokraticka republika,Kongo  demokratická republika,Kongo  demokraticna republika,Kongo  demokratična republika,Kongo  lydveldid,Kongo-Kinsasa,Kongo-Kinshasa,Kongoaen,Kongoi Demokratikus Koeztarsasag,Kongojy Demokraton Respublikae,Kongoko Errepublika Demokratikoa,Kongon Demokratine Tazovaldkund,Kongon demokraattinen tasavalta,Kongoo-Kinshasa,Kongoya Demokratik,Kongoya Demokratîk,Kongoän,Kongó - Kinshasa,Kongó  Demokratikus köztársaság,Kongó  lýðveldið,Kongó-Kinsásá,Kongói Demokratikus Köztársaság,Kongóo-Kinshasa,Konqo - Kinsasa,Konqo - Kinşasa,Konqo Demokratik Respublikasi,Konqo Demokratik Respublikası,Konzska demokraticka republika,Konžská demokratická republika,Kungu Runakamaq Ripuwlika,Kuoduoruosese ti Ngunuhalezo ti Kongoe,Kuonga Demuokratene Respobleka,Kuonga Demuokratėnė Respoblėka,Kéyah Káango Shádiʼááhjí Siʼánígíí,Ködörösêse tî Ngunuhalëzo tî kongö,Kùodùorùosêse tî Ngunuhalëzo tî Kongö,Laike Demokratia tou Kon'nko,Ndenndaandi Demokaraasiire Konngo,Orile-ede Olominira Oloselu ile Kongo,Orileede Kongo,Orilẹ́ède Kóngò,Orílẹ̀-èdè Olómìnira Olóṣèlú ilẹ̀ Kóngò,Pobblaght Gheynlagh ny Congo,Poblachd Dheamocrach na Congo,Poblacht Dhaonlathach an Chongo,Poblacht Dhaonlathach an Chongó,RDC,Rephabliki ya Demokrasi ya Kongo,Repibiki demokratiki ya Kongo,Repibiki demokratiki ya Kongó,Repoblek Werinel Kongo,Repoblika Demokratikani Kongo,Repoblikan'i Kongo,Repubblica Democratica del Congo,Repubblika Demokratika tal-Kongo,Repubbrica Democratica do Congo,Repubilika ya Kongo ya Dimokalasi,Repubilika ya Kôngo ya Dimokalasi,Republic of Zaire,Re",
                "latitude": -2.5,
                "longitude": 23.5,
                "feature_class": "A",
                "feature_code": "PCLI",
                "country_code": "CD",
                "cc2": "",
                "admin1_code": "00",
                "admin2_code": "",
                "admin3_code": "",
                "admin4_code": "",
                "population": 70916439,
                "elevation": 0,
                "gtopo30": 441,
                "timezone": "",
                "modification_date": "11/01/2015"
            },
            {
                "id": 39,
                "geoname_id": 3624060,
                "name": "Costa Rica",
                "ascii_name": "Republic of Costa Rica",
                "alternate_names": "Costa Rica,Costa Rice,Cot-xta Ri-ca,Còsta Rica,Cósta Ríce,Cốt-xta Ri-ca,Khosta Rikha,Kosita Lika,Kosita Rika,Kositarika,Kosta Riika,Kosta Rika,Kosta Rika nutome,Kosta Rikaa,Kosta Rikà,Kosta-Rika,Kosta-Ryka,Kostarika,Kostariko,Kostaryka,Kostaríka,Kwasta Rika,Kôsta Rîka,Kɔsitarika,Kɔsta Rika,Orileede Kuusita Rika,Orílẹ́ède Kuusita Ríkà,Republic of Costa Rica,Republica de Costa Rica,República de Costa Rica,ge si da li jia,i-Costa Rica,kastaryka,keasrrarikka,khxstarika,koseutalika,kosta rika,kostarika,kosutarika,kwstaryka,qwsth ryqh,Κόστα Ρίκα,Коста Рика,Коста-Рика,Коста-Рыка,Костарика,Կոստա-Ռիկա,קוסטה ריקה,كوستاريكا,کاستاریکا,کوسٹا ریکا,کۆستاریکا,कोष्टारिका,कोस्टारिका,कोस्टारीका,কোস্টারিকা,કોસ્ટા રિકા,କୋଷ୍ଟା ରିକା,கோஸ்டாரிகா,కోస్టారికా,ಕೊಸ್ಟಾ ರಿಕಾ,കോസ്റ്ററിക്ക,คอสตาริกา,ຄອສຕາລິກາ,ཀོ་ས྄ཊ་རི་ཀ།,ကော့စ်တာရီကာ,კოსტა-რიკა,ኮስታ ሪካ,កូស្តារីកា,コスタリカ,哥斯达黎加,코스타리카",
                "latitude": 10,
                "longitude": -84,
                "feature_class": "A",
                "feature_code": "PCLI",
                "country_code": "CR",
                "cc2": "",
                "admin1_code": "00",
                "admin2_code": "",
                "admin3_code": "",
                "admin4_code": "",
                "population": 4516220,
                "elevation": 0,
                "gtopo30": 1415,
                "timezone": "America/Costa_Rica",
                "modification_date": "02/05/2016"
            },
            {
                "id": 34,
                "geoname_id": 2287781,
                "name": "Côte d’Ivoire",
                "ascii_name": "Republic of Cote d'Ivoire",
                "alternate_names": "Aibari Kwas,Aibori Kot,Akte Elephantodontos,Akte Elephantostou,An Costa Eabhair,An Cósta Eabhair,Aod an Olifant,BK,Berderya Ac,Berderya Aç,Bjelokosna Obala,Bo Bien Nga,Breg na Slonova Koska,Bregu i Fildishte,Bregu i Fildishtë,Brjag na slonovata kost,Bờ Biển Ngà,Coasta de Fildes,Coasta de Fildeș,Costa Ivoria,Costa d'Avorio,Costa d'Avoriu,Costa d'Evori,Costa d'Ivori,Costa d'Ivur,Costa de Bori,Costa de Ebore,Costa de Marfil,Costa do Marfil,Costa do Marfil - Cote d'Ivoire,Costa do Marfil - Côte d'Ivoire,Costa do Marfim,Costa d’Ivori,Cote d'Iviethe,Cote d'Ivoire,Cote de l'Ivoire,Cote d’Ivoire,Couta d'Ivouero,Couta d’Ivouèro,Còsta d'Evòri,Côte d'Iviéthe,Côte d'Ivoire,Côte de l’Ivoire,Côte d’Ivoire,Dramblio KKR,Dramblio Kaulo Krantas,Ebur-Bordo,Eburbordo,Elefantcsontpart,Elefántcsontpart,Elevandiluurannik,Elfenbeenkuest,Elfenbeenküst,Elfenbein-Kuste,Elfenbein-Küste,Elfenbeinkueste,Elfenbeinküste,Elfenbeinskysten,Elfenbenariddu,Elfenbenskusten,Elfenbenskysten,Fil Disi Sahili,Fil Dişi Sahili,Filabeinsstroendin,Filabeinsstrondin,Fildisi Kiyisi,Fildisi Sahili,Fildisi Sahilleri,Fildişi Kıyısı,Fildişi Sahili,Fildişi Sahilleri,Fílabeinsstrondin,Fílabeinsströndin,Ivoarkust,Ivoorkus,Ivoorkust,Ivora Rivo,Ivori Sahili,Ivory Coast,Ivory Kost nutome,Ivory coast,Kodduwaar,Kodivaa,Kodivueaera,Kodiwari,Kosta ta' l-Avorju,Kosta ta’ l-Avorju,Kot d'Ivoar,Kot d'Ivuar,Kot-d'Ivuar,Kotdivuara,Kotdivuaro,Kotdivuāra,Kote Divwa,Kotedivuale,Kotedivuware,Kotídivualɛ,Kôdivüära,La Cote d'Ivoire,La Côte d'Ivoire,Litus Eburneum,Matafonua 'Aivili,Matafonua ʻAivili,Obala Bjelokosti,Obala Slonovace,Obala Slonovache,Obala Slonovače,Orileede Koute fora,Orílẹ́ède Kóútè forà,Pantai Gading,Pobrezi slonoviny,Pobrezie Slonoviny,Pobrežie Slonoviny,Pobřeží slonoviny,Republic of Cote d'Ivoire,Republic of Côte d’Ivoire,Republique de Cote d'Ivoire,République de Côte d’Ivoire,Slonokoscena obala,Slonokoščena obala,Wybrzeze Kosci Sloniowej,Wybrzeże Kości Słoniowej,a'ibari kosta,a'ibhari kosta,a'ibhori kosta,a'ivari kosta,abhari kosta,aiboli koseuteu,aivari keasrr,aivari kost,ayavhari kosta,hwp hsnhb,i-Ivory Coast,ke te di wa,koteudibualeu,kotojibowaru,prathes ko tdi waw r,xi wx ri khost,xiang ya hai an,İvori Sahili,Ακτή Ελεφαντοστού,Ακτή Ελεφαντόδοντος,Брег на Слонова Коска,Бряг на слоновата кост,Кот д'Ивоар,Кот д’Івуар,Кот д’Ивоар,Кот д’Ивуар,Кот-д'Івуар,Кот-д'Ивуар,Кот-д’Ивуар,Обала Слоноваче,Փղոսկրի Ափ,חוף השנהב,آئیوری کوسٹ,ساحل العاج,ساحل عاج,عاج ساحل,كوتى دى ئىۋۇئېر,کۆتدیڤوار,आइभोरी कोष्ट,आइवरी कोस्ट,आयव्हरी कोस्ट,আইভরি কোস্ট,আভরি কোস্ট,આઇવરી કોસ્ટ,ଆଇବରୀ କୋଷ୍ଟ,ஐவரி கோஸ்ட்,ఐవరీ కోస్ట్,ಐವರಿ ಕೋಸ್ಟ್,ഐവറി കോസ്റ്റ്,අයිවරි කෝස්ට්,ประเทศโกตดิวัวร์,ไอวอรี่โคสต์,ຝັ່ງທະເລໄອວໍລິ,ཀོ་ཊེ་ཌི། ཨི་ཝོ་རེ།,အိုင်ဗရီကိုစ့်,კოტ-დ'ივუარი,სპილოს ძვლის სანაპირო,ኮት ዲቯር,កូដឌីវ័រ,コートジボワール,科特迪瓦,象牙海岸,아이보리 코스트,코트디부아르",
                "latitude": 8,
                "longitude": -5.5,
                "feature_class": "A",
                "feature_code": "PCLI",
                "country_code": "CI",
                "cc2": "",
                "admin1_code": "00",
                "admin2_code": "",
                "admin3_code": "",
                "admin4_code": "",
                "population": 21058798,
                "elevation": 0,
                "gtopo30": 257,
                "timezone": "Africa/Abidjan",
                "modification_date": "05/02/2015"
            },
            {
                "id": 43,
                "geoname_id": 3077311,
                "name": "Czechia",
                "ascii_name": "Czechia",
                "alternate_names": "An tSeic,Bohemia,Ceahkka,Cechia,Cecland,Ceehi,Cehia,Cehija,Cehio,Cehujo,Cek Cumhuriyeti,Ceki republiki,Cekia,Cekija,Cekijos Respublika,Ceko,Cekya,Ceska,Ceska Republika,Ceska Socialisticka Republika,Ceska republika,Ceske Kraje,Ceske Uzemi,Ceske Zeme,Cesko,Cex Respublikasi,Chekhi,Chekhija,Chekia,Chekkia,Chequia,Chequia - Cesko,Chequia - Česko,Ches'ka respublika,Chesh'sko,Cheshka,Cheshka Republika,Cheshskaja Respublika,Chexiya,Chik Suyu,Chéquia,Cong hoa Sec,Cong hoa Sec (Czech),Cseh Koeztarsasag,Cseh Köztársaság,Csehorszag,Csehország,Czech Lands,Czech Republic,Czech Socialist Republic,Czechia,Czechy,Czesko Republika,Czeskô Repùblika,Cộng hòa Séc,Cộng hòa Séc (Czech),Ditunga dya Tsheka,Gweriniaeth Tsiec,Jamhuri ya Cheki,Jamhuriyar Cak,Jamhuuriyadda Jek,Kekkia,Koedoeroesese ti Tyeki,Komara Cekiyaye,Komara Çêkiyayê,Kyɛk Kurokɛse,Ködörösêse tî Tyêki,Lipapilika Seki,Lipubulika ya Ceeka,Ndenndaandi Cek,Orileede seeki,Orílẹ́ède ṣẹ́ẹ́kì,Poblacht na Seice,Repibiki Tsekɛ,Repoblikan'i Tseky,Repubblica Ceca,Repubblika Ceka,Repubblika Ċeka,Repubbrica Ceca,Republica Ceca,Republica Ceha,Republica Cehă,Republica Chec,Republica Checa,Republica Chèca,Republica Tchec,Republica Tcheca,Republica Tscheca,Republica Txeca,Republiche Ceche,Republik Ceko,Republik Czech,Republik Czechia,Republik Tchek,Republika Ceke,Republika Ceska,Republika Chekhija,Republika Czeka,Republika Czeska,Republika e Cekise,Republika e Çekisë,Republika Çeke,Republika Češka,Republique tcheque,Republyique Tcheque,Repubulika ya Ceke,Repùblica Ceca,República Checa,República Tcheca,República Txeca,Res publica Bohemica,Ripubblica Ceca,Ripublica Cecca,Ripùbblica Ceca,Rèpublica tch·èca,République tchèque,Républyique Tchèque,Tchequia,Tchequie,Tchéquia,Tchéquie,Teehhi,Tekkland,Tjeckien,Tjeggiese Republiek,Tjekkia,Tjekkiet,Tschechesch Republik,Tschechien,Tschechische Republik,Tschjechje,Tsechia,Tsehhi,Tsehhi Vabariik,Tsekin tasavalta,Tsekki,Tsjechie,Tsjechië,Tsjechje,Tsjeggie,Tsjeggië,Tsjekkia,Tsyegaen,Tsyegän,Tsɛk repɔblik nutome,Txekiar Errepublika,Txequia,Txèquia,Tékkland,Těehhi,Tšehhi,Tšehhi Vabariik,Tšekki,Ucheki,Yn Pobblaght Sheckagh,cek ganarajyam,cek kutiyaracu,cek ripablik,cek sadharanatantra,ceka ganarajya,ceka prajasattaka,ceka prajatantra,ceka ripablika,cekha ganatantra,cekiya,cekk rippablik,ceqa ganatantra,chekheti,cheko,cheko gong he guo,chekogonghwagug,i-Czech Republic,jheka prajasattaka,jie ke,jie ke gong he guo,jmhwry chk,jmhwryt altshyk,sa tharn rath chek,tshyk,z'kyh,Çek Cumhuriyeti,Çekia,Çekya,Çex Respublikası,Ĉeĥio,Ĉeĥujo,Čeahkka,Čeehi,Čehija,Čekija,Čekijos Respublika,Česko,Česká Socialistická Republika,Česká republika,České Kraje,České Země,České Územi,Češka,Češka Republika,Češka republika,Čhekkia,Čěska republika,Τσεχία,Република Чехия,Чеська республіка,Чехiя,Чехи,Чехия,Чехія,Чешка,Чешка Република,Чешская Республика,Чешьско,Чэхія,Չեխիայի Հանրապետություն,טשעכיע,צ'כיה,צ׳כיה,تشيك,جمهورية التشيك,جمهوری چک,چیک جمہوریہ,چېک جمهوريت,کۆماری چیک,ܬܫܝܟ,चेक गणराज्य,चेक प्रजासत्ताक,चेक रिपब्लिक,चेक़ गणतंत्र,चेख गणतन्त्र,झेक प्रजासत्ताक,চেক প্রজাতন্ত্র,চেকিয়া,চেকিয়া,ચેક રીપબ્લિક,ଚେକ୍ ସାଧାରଣତନ୍ତ୍ର,செக் குடியரசு,చెక్ గణరాజ్యం,ಚೆಕ್ ರಿಪಬ್ಲಿಕ್,ചെക്ക് റിപ്പബ്ലിക്,สาธารณรัฐเช็ก,ສາທາລະນະລັດເຊັກ,ཅེ་ཁེ,ཅེཀ་རི་པབ་ལིཀ,ཅཻག་སྤྱི་མཐུན་རྒྱལ་ཁབ།,ချက် ပြည်ထောင်စု,ჩეხეთი,ჩეხეთის რესპუბლიკა,ቼክ ሪፑብሊክ,សាធារណរដ្ឋឆេក,チェコ,チェコ共和国,捷克,捷克共和国,체코,체코공화국",
                "latitude": 49.75,
                "longitude": 15,
                "feature_class": "A",
                "feature_code": "PCLI",
                "country_code": "CZ",
                "cc2": "",
                "admin1_code": "00",
                "admin2_code": "",
                "admin3_code": "",
                "admin4_code": "",
                "population": 10476000,
                "elevation": 430,
                "gtopo30": 439,
                "timezone": "Europe/Prague",
                "modification_date": "01/25/2017"
            },
            {
                "id": 46,
                "geoname_id": 2623032,
                "name": "Danmark",
                "ascii_name": "Kingdom of Denmark",
                "alternate_names": "An Danmhairg,Daeaenmark,Daenemark,Danaen,Danemalaku,Danemarc,Danemarca,Danemark,Danemarka,Danemarki,Danemerke,Danemârc,Danemêrke,Dani,Dania,Danija,Danimarca,Danimariki,Danimarka,Danimarke,Danimarkë,Danio,Danmak,Danmark,Danmarka,Danmarki,Danmarku,Danmoerk,Danmork,Danmörk,Danmørk,Dannemar,Danska,Dansko,Dansuyu,Danujo,Danän,Danîmarka,Danɛmarike,Denamarka,Denemarcken,Denemark,Denemarke,Denemarken,Denemarrick,Denemearc,Denimaaka,Denmakhi,Denmaki,Denmarc,Denmark,Denmark nutome,Denmarki,Densko,Dinamarca,Dinamarca - Danmark,Dinamarka,Dánia,Dánmárku,Dánsko,Dänemark,Däänmark,Dëńskô,Dānija,Dɛnmak,GJan Mach,Kingdom of Denmark,Kongeriget Danmark,Orileede Demaki,Orílẹ́ède Dẹ́mákì,Taani,Tanska,Tenima'ake,Tenimaʻake,Yn Danvarg,aldanmrk,aldnmark,dan mai,dania,danmark,denamarka,denmakeu,denmaku,denmaku wang guo,denmark,denmarka,denmaർkk,dnmrq,dʾnmʾrq,i-Denmark,prathes denmark,tenmark,Đan Mạch,Δανία,Дани,Дания,Данска,Данія,Դանիա,דנמרק,דענמארק,الدانمرك,الدنمارك,دانمارک,دانىيە,ڈنمارک,ډنمارک,ډېنمارک,ܕܐܢܡܐܪܩ,डेनमार्क,डेन्मार्क,ডেনমার্ক,ডেন্মার্ক,ડેનમાર્ક,ଡେନମାର୍କ,டென்மார்க்,డెన్మార్క్,ಡೆನ್ಮಾರ್ಕ್,ഡെന്മാർക്ക്,ഡെന്‍മാര്‍ക്ക്,ඩෙන්මාර්කය,ประเทศเดนมาร์ก,เดนมาร์ก,ເດນມາກ,ཌེན་མཱཀ,ཌེན་མཱརྐ།,དན་མྲག,ဒိန်းမတ်,დანია,ዴንማርክ,ដាណឺម៉ាក,Ḍēnamārka,デンマーク,デンマーク王国,丹麦,덴마크",
                "latitude": 56,
                "longitude": 10,
                "feature_class": "A",
                "feature_code": "PCLI",
                "country_code": "DK",
                "cc2": "",
                "admin1_code": "00",
                "admin2_code": "",
                "admin3_code": "",
                "admin4_code": "",
                "population": 5484000,
                "elevation": 0,
                "gtopo30": 50,
                "timezone": "Europe/Copenhagen",
                "modification_date": "11/16/2016"
            },
            {
                "id": 169,
                "geoname_id": 1966436,
                "name": "Democratic Republic of Timor-Leste",
                "ascii_name": "Democratic Republic of Timor-Leste",
                "alternate_names": "Anatoliko Timor,Aslagang Timor,Aust-Timor,Austrumtimora,Austur-Timor,Austur-Tímor,Colonia de Timor,Colónia de Timor,Daya a Timor,Democratic Republic of Timor-Leste,Dogu Timor,Dong Ti-mo,Doğu Timor,Dwyrain Timor,East Timor,East-Timor,Ekialdeko Timor,Estal Timor,Eystur-Timor,Ida Timor,Ida-Timor,Istochen Timor,Istochni Timor,Istocni Timor,Istočni Timor,Itae-Timor,Itä-Timor,Iztochen Timor,Kelet-Timor,Kɔrɔn Timɔr,Lofueda-Timoreaen,Lofüda-Timoreän,Loro Sae,Nuorta-Timor,OEsttimor,Oos-Timor,Oost-Timor,Oosttimor,Orienta Timoro,Orileede IlaOorun Timo,Orílẹ́ède ÌlàOòrùn Tímọ̀,Ost-Timor,Osttimor,Portuguese Timor,Propinsi Timor Timur,Province of Timor,Provincia de Timor,Província de Timor,Republica Democratica de Timor-Leste,Republika Demokratika Timor Lorosa'e,República Democrática de Timor-Leste,Repúblika Demokrátika Timor Lorosa’e,Rytu Timoras,Rytų Timoras,Shidnij Timor,Silangang Timor,Timoa Hahake,Timoor Fuɗnaange,Timor Atsinanana,Timor Est,Timor Kangilliit,Timor Leste,Timor Lorosa'e,Timor Lorosae,Timor Lorosa’e,Timor Oriental,Timor Ta Gabas,Timor Timur,Timor Wschodni,Timor da l'Ost,Timor del Est,Timor ekialdea,Timor oriental,Timor orientâl,Timor tal-Lvant,Timor-Leste,Timor-Leste nutome,Timor-Lesti,Timora Rojhilat,Timori Lindor,Timori Mashariki,Timori ya Mashariki,Timoria Orientalis,Timorka bari,Timoro ti Toe,Timoru wa diboku,Timoru y'iburasirazuba,Timorul de Est,Timorɛ ya Moniɛlɛ,Timowa,Timòr Èst,Timór Lorosae,Timôro tî Tö,Timɔ Boka,Tiomor Thoir,Tymor-Lesci,Tíomór Thoir,Tîmora Rojhilat,Ushodni Tymor,Vostochnyj Timor,Vychodni Timor,Vychodny Timor,Vzhodni Timor,Východní Timor,Východný Timor,Wuchodny Timor,dong di wen,dongtimoleu,dongtimoru,dongtimoru gong he guo,i-East Timor,ist timor,kilakku taimor,mzrh tymwr,prathes timxr-les te,purba timor,purba timora,purva timora,purvi timora,timxr tawan xxk,turpu timor,tymr shrq,tymwr alshrqyt,tymwr hmzrhyt,tymwr shrqy,Ðông Ti-mo,Östtimor,Øst-Timor,Østtimor,Şərq Timor,Şərqi Timor,Ανατολικό Τιμόρ,Восточный Тимор,Източен Тимор,Источен Тимор,Источни Тимор,Східний Тимор,Тимор-Лесте,Тымор-Лешці,Тімор-Лешті,Усходні Тымор,טימור המזרחית,מזרח טימור,تيمور الشرقية,تیمر شرق,تیمور شرقی,تیمور لیسٹ,تیمۆری ڕۆژھەڵات,ختيځ ټيمور,पूर्व तिमोर,पूर्वी टिमोर,पूर्वी तिमोर,পূর্ব টিমোর,પૂર્વ તિમોર,ପୁର୍ବ ତିମୋର୍,கிழக்கு தைமோர்,తూర్పు టిమోర్,ಈಸ್ಟ್ ಟಿಮೋರ್,കിഴക്കന്‍ തിമോര്‍,ติมอร์ตะวันออก,ประเทศติมอร์-เลสเต,ຕິມໍຕາເວັນອອກ,အရှေ့တီမော,აღმოსავლეთი ტიმორი,ምስራቅ ቲሞር,ទីម័រខាងកើត,东帝汶,東ティモール,東ティモール共和国,동티모르",
                "latitude": -8.83333,
                "longitude": 125.75,
                "feature_class": "A",
                "feature_code": "PCLI",
                "country_code": "TL",
                "cc2": "",
                "admin1_code": "00",
                "admin2_code": "",
                "admin3_code": "",
                "admin4_code": "",
                "population": 1154625,
                "elevation": 0,
                "gtopo30": 1419,
                "timezone": "Asia/Dili",
                "modification_date": "03/06/2013"
            },
            {
                "id": 100,
                "geoname_id": 1227603,
                "name": "Democratic Socialist Republic of Sri Lanka",
                "ascii_name": "Democratic Socialist Republic of Sri Lanka",
                "alternate_names": "Ceilan,Ceilán,Cejlono,Ceylon,Democratic Socialist Republic of Sri Lanka,Dominion of Ceylon,Ilankaic Cananayaka Cocalicak Kutiyarcu,Isla Trapobana,Lanka,Lanka-dipa,Lanka-dvipa,Lanka-dvīpa,Lanka-dīpa,Lankava,Lankāva,Orileede Siri Lanka,Orílẹ́ède Siri Lanka,Prajatantravadi Samajavadi Janarajaya Sri Lanka,Selan,Serendib,Shri Lanka,Shri-Lanka,Shry-Lanka,Sihala-dvipa,Silangika,Silangikā,Siri Lanka,Siri-Lanka,Sirilaanka,Sirilanka,Sirî-Lanka,Sri Lan'ka,Sri Lanca,Sri Langka,Sri Lanka,Sri Lanka Janarajaya,Sri Lanka nutome,Sri Lankā Janarajaya,Sri-Lanka,Sri-Lanko,Srilanka,Srí Lanca,Srí Lanka,Sīhala-dvīpa,Tamaraparni,Taprobane,Trapobana,Tāmaraparnī,Xri Lan-ca,Xri Lan-ca (Sri Lanka),i-Sri Lanka,ilankai,seulilangka,si li lan ka,sri langka,sri lanka,srilanka,sry lanka,sry lnka,sry lnqh,srylanka,suriranka,suriranka min zhu she hui zhu yi gong he guo,Şri Lanka,Šri Lanka,Šrilanka,Σρι Λάνκα,Шри Ланка,Шри-Ланка,Шры-Ланка,Шрі Ланка,Шрі-Ланка,Շրի Լանկա,סרי לנקה,سري لانكا,سريلانكا,سری لانکا,سری لنکا,سریلانکا,سری‌لانکا,श्री लंका,श्रीलंका,श्रीलङ्का,শ্রীলঙ্কা,શ્રીલંકા,ଶ୍ରୀଲଙ୍କା,இலங்கை,శ్రీలంక,ಶ್ರೀಲಂಕಾ,ശ്രീലങ്ക,ශ්‍රී ලංකාව,ศรีลังกา,ສີລັງກາ,ཤྲཱི་ལངྐ་།,ཤྲཱྀ་ལངཀ,သီရိလင်္ကာ,შრი-ლანკა,ሲሪላንካ,ស្រីលង្កា,スリランカ,スリランカ民主社会主義共和国,斯里兰卡,스리랑카",
                "latitude": 7.75,
                "longitude": 80.75,
                "feature_class": "A",
                "feature_code": "PCLI",
                "country_code": "LK",
                "cc2": "",
                "admin1_code": "00",
                "admin2_code": "",
                "admin3_code": "",
                "admin4_code": "",
                "population": 21513990,
                "elevation": 0,
                "gtopo30": 394,
                "timezone": "Asia/Colombo",
                "modification_date": "11/08/2013"
            },
            {
                "id": 45,
                "geoname_id": 223816,
                "name": "Djibouti",
                "ascii_name": "Republic of Djibouti",
                "alternate_names": "Afars and Issas,Chibuti,Ciboti,Cibutaen,Cibuti,Cibutän,Cote Francaise des Somalis,Cîbûtî,Côte Française des Somalis,Dibutuii,Dibutùii,Diobuiti,Diobutaidh,Diobùtaidh,Diobúití,Djiboeti,Djiboti,Djibouti,Djibuti,Dj·iboti,Djíbútí,Dschibuti,Dzhibuti,Dzibuti,Dzibuti nutome,Dzibutija,Dzibutis,Dzibutsko,Dzsibuti,Dzybuci,Dżibuti,Džibuti,Džibutija,Džibutis,Džibutsko,French Somali Coast,French Territory of Afars and Issas,Gi-bu-ti,Gibuti,Gibutio,Gibutum,Gyibuti,Hiboti,Jabuuti,Jiboti,Jibouti,Jibuti,Jibutii,Jjibuti,Orileede Dibooti,Orílẹ́ède Díbọ́ótì,Republic of Djibouti,Republique de Djibouti,République de Djibouti,Siputi,Somalie Francaise,Somalie Française,Territoire Francais des Afars et des Issas,Territoire Français des Afars et des Issas,Territoire de la Cote Francaise des Somalis,Territoire de la Côte Française des Somalis,Territory of French Somaliland,Tzimpouti,Xhibuti,Xibuti,Yabuuti,Yibuti,ci buti,dibauti,dijibuti,gybwty,i-Djibouti,jbwty,ji bu ti,jibauti,jiboti,jibuchi,jibuti,jibutti,jipautti,jybwty,jybwwty,prathes ci buti,Ĝibutio,Ġibuti,Τζιμπουτί,Џибути,Джибути,Джыбуці,Джібуті,Ҷибути,Ջիբուտի,גיבוטי,ג׳יבוטי,جبوتی,جىبۇتى,جيبوتي,جیبوتی,جیبووتی,جېبوتي,जिबूती,जिबौटी,डिजिबुटी,জিবুতি,જીબૌટી,ଡିବୌଟି,ஜிபௌட்டி,జిబౌటి,ಜಿಬೋಟಿ,ജിബൂട്ടി,จิบูตี,ประเทศจิบูตี,ຄິໂບຕິ,ཛི་བུ་ཏི།,ჯიბუტი,ጂቡቲ,ጅቡቲ,ហ្ស៉ីបូទី,ジブチ,吉布提,지부티",
                "latitude": 11.83333,
                "longitude": 42.5,
                "feature_class": "A",
                "feature_code": "PCLI",
                "country_code": "DJ",
                "cc2": "",
                "admin1_code": "00",
                "admin2_code": "",
                "admin3_code": "",
                "admin4_code": "",
                "population": 740528,
                "elevation": 0,
                "gtopo30": 986,
                "timezone": "Africa/Djibouti",
                "modification_date": "10/30/2015"
            }]
    }
}